### ISSUE TITLE
bailey des generation fails under `crawl -test`

### ISSUE THREAD

**Issue by alexjurkiewicz** [crawl/crawl#1121]
If you run crawl as `./crawl -test` with an empty DES cache, it fails:

```
$ rm -rf ~/Library/Application\ Support/Dungeon\ Crawl\ Stone\ Soup/
$ ./crawl -test
[...]
Regenerating des: ./dat/des/portals/bailey.des
./dat/des/portals/bailey.des:368: Couldn't find a map for bailey_axe
$
```

`./crawl -builddb` and `./crawl` work fine.

**Comment by rawlins** [comment]
I think `crawl -test` explicitly isn't supposed to regenerate the des cache, and I'm not entirely sure why it's regenerating anything at all, so an error when you do this is expected. However, I agree that this particular error is confusing. I looked into why this happens a few months ago, and it seems to basically be the first error that happens if you run the des lua in order with no existing des cache after game start (the bit of lua code that leads to this error doesn't run on builddb), and the specific error is because the `bailey` map tries to find a bailey tagged vault to place before any of those have been processed, so if there is no cache, it doesn't find any at all.

**Comment by rawlins** [comment]
> I'm not entirely sure why it's regenerating anything at all

for the record, It's not actually regenerating the cache, but the entire des cache (?) seems to be run on startup in any case.

**Comment by alexjurkiewicz** [comment]
Nice!!
