### ISSUE TITLE
Strange '</lightgreen>' message output in tiles mode

### ISSUE THREAD

**Issue by RMGiroux** [crawl/crawl#1224]
**PLATFORM and OS or BROWSER:**  
webtiles

**DCSS VERSION:** 
0.25-a0-258-g6d7e32a812

**DESCRIPTION:**
Some colored text in webtiles has strange closing html tags after it.
e.g.: Found a glowing spear.&lt;/lightgreen&gt;

**EXTRA FILES:**
*Please include any morgue files, crashlogs, save files here, or extra
screenshots here. If this is a crash bug, the crashlog and save file will be
extremely helpful; the location of these is sytem-specific but if you ask
we can help you find them.*

*To upload a save file directly to github, compress it to a .zip archive, and
then github will accept the upload. (It will not take a .cs file directly.)*

*If this is an online game, see [these instructions](https://crawl.develz.org/wiki/doku.php?id=mantis:savebackup)
for more information on how to make a save backup; you can provide the
resulting link here.*

**Comment by Goratrix** [comment]
This was also reported by kaninmat in discord, who mentioned that he has this line in his rcfile, so that's most likely the culprit:

> message_colour ^= lightgreen:Found

**Comment by RMGiroux** [comment]
That might do it.  Checking my rc file, I found:

```lua
message_colour ^= lightgreen:Found
message_colour ^= green:more experienced
message_colour ^= magenta:sizzling sound
message_colour ^= red:you shout at
```

But I don't recall seeing any closing tags other  than the `</lightgreen>`.  I might have missed them though...

**Comment by Goratrix** [comment]
It's probably just the lightgreen one, there's has been a recent change for Found messages only. Something in this formatting must be causing the end tag to get duplicated:

https://github.com/crawl/crawl/commit/dbf363a7764abcd79cc012143a4f204229082a87

**Comment by aidanholm** [comment]
Thanks for reporting! This happens because `formatted_string` does not support nested colours: E.g. `"<grey>hello<green>world</green>!</grey>"` will get converted to `<grey>hello<green>world<grey>!` internally, and `to_colour_string()` will produce this flattened format. `mpr()` will then wrap this with `<lightgreen>` and `</lightgreen>`, which causes a syntax error.

I'm working on a fix (namely, update `formatted_string` to internally store the nested colours properly)
