### ISSUE TITLE
Crash on trying to enter the Temple

### ISSUE THREAD

**Issue by loewenheim** [crawl/crawl#1225]
**PLATFORM and OS or BROWSER:**
Both local tiles and ASCII on NixOS. Game installed from the `nixos-unstable` channel.

**DCSS VERSION:**
0.24.0

**DESCRIPTION:**
When trying to enter the temple, the game crashes with
`ERROR in 'dbg-scan.cc' at line 687: Exit exit_bailey[154] didn't get generated.`

**EXTRA FILES:**
Crash report & save file.

[crash.zip](https://github.com/crawl/crawl/files/3936385/crash.zip)

**Comment by rawlins** [comment]
Thanks for the report. When looking at the crashlog I noticed the following lines:

```
/nix/store/frnklcjj66a1lc9qnr5cqr9qxnkdzc1y-crawl-0.23.2-tiles/dat/des/portals/
bailey.des:574: Bad item name: 'tomahawk'
/nix/store/frnklcjj66a1lc9qnr5cqr9qxnkdzc1y-crawl-0.23.2-tiles/dat/des/portals/
bailey.des:564: in main chunk x25
```

This looks like the 0.24.0 install is using the wrong des files, from a previous 0.23.2 install; the two sets of des files aren't compatible. The crash is because the bailey failed to fully place because of incompatible items in the two versions (tomahawks don't exist in 0.24).

This is most likely a downstream packaging issue in that `/nix/store/frnklcjj66a1lc9qnr5cqr9qxnkdzc1y-crawl-0.23.2-tiles/` looks os-specific and it is largely up to specific packaging systems where they will install the support files. It does look like the crawl binary with the crash report was build to use `/nix/store/1qy4nanv5j1iz1gnhyma3ick15yr6rld-crawl-0.24.0/`, does that directory exist? It would also be useful to paste what crawl shows when you hit `ctrl-p` from the main menu. Beyond that I don't know enough about nixos to really diagnose how it would have managed to find the wrong data directory.

As a brute-force workaround the first thing to try might be to fully uninstall 0.23.2 and reinstall 0.24.0, if that is possible.

**Comment by rawlins** [comment]
Also, if the two versions use a shared save directory in nixos, try deleting the subdirectory `des/` under there.

**Comment by loewenheim** [comment]
Thank you for your reply. Deleting the `des` directory did indeed fix the problem! For the sake of completeness, here is the output of `ctrl-p` in the main menu:
```
Data directory '/nix/store/1qy4nanv5j1iz1gnhyma3ick15yr6rld-crawl-0.24.0/dat/'
 found.
 Loading databases... Loading spells and features... Loading maps...
 Hello, welcome to Dungeon Crawl Stone Soup 0.24.0!
 (c) Copyright 1997-2002 Linley Henzell, 2002-2019 Crawl DevTeam
 Options read from
 "/nix/store/1qy4nanv5j1iz1gnhyma3ick15yr6rld-crawl-0.24.0/settings/init.txt".
```
Everything seems to be ok on that front.
