### ISSUE TITLE
Sif Piety generation broken?

### ISSUE THREAD

**Issue by joemaro** [crawl/crawl#1238]
Crawl version: 0.25-a0-299 offline tiles client on Linux 64 bit

I've had this problem several times now, that Sif's piety just doesn't max out or leaks somehow. I can't pin it yet, but the following game should be a good and clear indicator:

Started to follow Sif early on D:4 with Amulet of Faith. Reached 5 stars of piety on D:9 (after being shafted to D:11 before that), then cleared lair, orc, then down to D:15. Now i have both S-Runes and piety is *still* stuck at 5 stars. 6 stars hasn't been reached ever in that game. I maybe used `Channel Magic` twice in all that time...

There's gotta be a piety leak somewhere in the code, but i'm not good at programming so i can't help there, sorry.

Here's the morgue: 

[Ilio.txt](https://github.com/crawl/crawl/files/3992785/Ilio.txt)

**Comment by Goratrix** [comment]
This has been discussed a lot in discord and gammafunk confirmed that the piety gain is working fine. The reason why you don't reach 6* is that she gifts too often. Below is copy/pasted from discord, all written by Wise Wolf (byrel):

------------------------------------------------------------------------------------------------
Sif piety code-dive:
OK. So the way gifting with piety gain works is:

Piety gain:
--If you have a gift timeout, decrement by 1 and then return doing nothing 75% of the time
otherwise
--If you're 6* or above, 55% of the time don't gain piety.
--If you're 4* or above, 33% of the time don't gain piety.
-- otherwise gain the piety
-- regardless, attempt to give a gift if gift timeout is 0.

The way Sif gifts work:
--If gift timeout is 0 and you're at 5 stars and random2(piety) > 100 and it won't drop in lava, and you don't know all spells, give a gift and increment gift_timeout by 40+2d9

The way Trog gifts work:
--If gift timeout is 0, and you're eligible for weapon gifts, if random2(piety)>100 then 25% of the time gift a weapon and increment gift_timeout by 30+2d9
--If gift timeout is 0, and you weren't given a weapon gift (for any reason), and you're eligible for ammo gifts then if random2(piety)>70 and 1d12 <= (1 + best-ranged-skill),  then 12.5% of the time give an ammo gift and increment gift_timeout by 4+2d4

Takeaways:
--When you're not eligible for a gift due to gift timeout, piety gain is 25% of normal.
--Trog at 159 piety (just below 6 stars) and 0 gift_timeout and >=11 in some ranged skill, has a 7.3% chance of gifting you a weapon when you gain piety, and a 5.1% chance of giving you ammo. Which means you have an 12.5% chance each time you're eligible for a gift of receiving one and otherwise you continue to gain piety at your normal rate.
--With Sif at 159 piety and 0 gift_timeout has a 30% chance of receiving one and otherwise you continue to gain piety at your normal rate.
(Oka works like trog except that half the weapon gifts are converted into armour gifts, and the armour gifts increment gift_timeout by almost twice as much.)
So the problem with Sif piety gain, IMO, is that she's too generous with her gifts. I think adding a 1 in 4 chance to her gifting would improve the feel of her piety gain to be similar to Trog/Oka.
On the player side, if you're really desperate for Sif 6* for tourney points or something you can abuse the 'won't give gifts over lava' by going to abyss 5, flying over deep water/lava, and reading a scroll of noise and killing all the things while flying. (I recommend Gargoyle/Tengu/Draconians for permaflight. And really not minding if you splat for your own mental health.)
------------------------------------------------------------------------------------------------

**Comment by joemaro** [comment]
Thanks a lot @Goratrix for the clarification!

i'm still playing that game and am pretty close to the the 3rd rune, yet no 6* reached, which doesn't bother gameplay wise, it just feels odd.

Seeing that the source was checked, i'll close this.

ps: if the discussion would've happened in IRC, i would've been part of it i guess, just wanna raise my voice against discord here :P
