### ISSUE TITLE
local tiles: Don't Hardcode Font

### ISSUE THREAD

**Issue by travankor** [crawl/crawl#1344]
**PLATFORM and OS or BROWSER:**
local tiles, OS: Linux

**DCSS VERSION:**
0.24.1

**DESCRIPTION:**
Is there a reason why DCSS tiles is hard-coded to dejavu mono? Can it use fontconfig instead like most other applications do these days? There are fonts that are metric-compatible with dejavu, like bitstream-vera, and DCSS hard-refuses to launch tiles without dejavu.

**Comment by aidanholm** [comment]
Have you tried using `tile_font_crt_file` and related options?

DCSS does things this way for historical reasons, as always. Using fontconfig would probably be a good idea if it's supported on msys, which it does seem to be; it'd likely require vendoring the fontconfig repository and making some changes to the Makefile, both of which are quite toilsome.

**Comment by rawlins** [comment]
For the general situation, I think the hardcoding situation is not so dire as this issue makes it look: crawl needs *some* font to be around to run, and deja vu mono is the one we distribute with crawl binaries and keep in the repo as a contrib. It is overrideable with `tile_font_crt_file` as @aidanholm suggests, and the game will start without deja vu as long as a valid font is specified this way. This could definitely be improved but it seems ok in general for me now. So in general I would say this is basically wontfix.

However, I wonder if this issue may have actually been about debian packaging and not crawl in general? There we do seem to hardcode a path in `/usr/share/fonts/` rather than distributing the font or finding that path automatically, which seems pretty non-ideal to me. Even on debian it looks to me like as long as some valid font is specified explicitly in the crawlrc file, it can start without the `/usr/share/fonts/` version of deja vu. I don't know enough about debian to easily fix this myself though.

**Comment by ebering** [comment]
Absent further follow-up from the reporter about this being a Debian specific issue, and any newer reports about font issues with debs, I'm going to close this as wontfix.

**Comment by rawlins** [comment]
I'm going to reopen this, because I think it is our bug (not a downstream bug) and what we do in the generated debian packages is far from ideal. Here's a concrete statement of the issue:

* When generating the debs, we have a harcoded path to what (hopefully?) would be a reliable location to find deja vu.
* Specifically, at https://github.com/crawl/crawl/blob/1a8b9f50bf3c6ad330e7a2764013c47af3c2aea7/crawl-ref/source/debian/rules#L64 these are hardcoded to `/usr/share/fonts/truetype/`.
* This is in contrast to the mac and the windows builds, where this font is distributed as a contrib.
* I don't know enough about debian packaging to fix this myself, but one obvious thing to check is what the downstream debs *do* actually do, since this is the kind of thing they usually fix up for official debs. As the original reporter suggests, this ought to at least find the font location, not assume it.
