### ISSUE TITLE
save file decompression failed

### ISSUE THREAD

**Issue by jonEndy** [crawl/crawl#1345]
Windows 10, playing the game locally off of a flash drive

0.24 stable

When clicking on my saved game file I am presented with the error shown in the screenshot.  There seems to be no way around it and the game closes

![error(1)](https://user-images.githubusercontent.com/63506616/79046720-32950200-7bd8-11ea-84d2-84cbb8f6c9f1.PNG)
![error(2)](https://user-images.githubusercontent.com/63506616/79046721-332d9880-7bd8-11ea-8a06-466ac9d6d04e.PNG)

**Comment by rawlins** [comment]
Can you upload the save file? Github will allow you to do that if you zip it.

In general this error is pretty much what it sounds like, it'll result from the save file being corrupted somehow. It's not impossible that this would happen from removing a flash drive without properly unmounting in some OSs, but it's hard to say from a distance what other causes there might be. It's conceivable that the save file is salvageable but one of us would need to look at it.

**Comment by jonEndy** [comment]
[saveFile.zip](https://github.com/crawl/crawl/files/4464873/saveFile.zip)

Can do!

This is not my first time experiencing this error and since I last encountered it I have been sure to get the all clear "Safe To Remove" message prior to disconnecting the flash drive.  Though that could be just a false sense of security.

**Comment by rawlins** [comment]
I was not able to fully repair the save file and it isn't immediately obvious how this could have happened, but Spider 3 and 4 are corrupted; the rest of the save seems to be ok on a quick check. Here is a save that has had those maps deleted, and your character moved on top of an arbitrary down stair on spider:2, otherwise no changes. If you descend it will regenerate new levels for spider 3 and 4, but I don't really recommend doing that given that you already have the gossamer rune. I'm afraid any floor items, shops, etc you had on those levels are gone for good in this save -- but it will hopefully be playable and the savefile edit only affects a couple of what I would guess are mostly-cleared levels.

[Marshal.cs.zip](https://github.com/crawl/crawl/files/4464940/Marshal.cs.zip)

**Comment by jonEndy** [comment]
Fantastic!

Thank you.  I suppose I'll just start keeping a running copy on a hard drive so if it does happen again I at least don't lose everything.

**Comment by rawlins** [comment]
I'm going to close this as it doesn't seem like replicating it will be immediately possible. This does remind me of https://crawl.develz.org/mantis/view.php?id=11960 though, where a save file was corrupted apparently related to google drive sync.
