### ISSUE TITLE
Across-the-board background nerf

### ISSUE THREAD

**Issue by RojjaCebolla** [crawl/crawl#1477]
Most of the starter kits in DCSS can "carry you to lair". There are some jobs that are crummier or, to euphemize it, "more reliant on luck and floor items", but you can get an EE, CJ, FI, AK, GL etc through the early game without having to evaluate using a potentially-cursed item.

This can contribute to a few problems:

- floor item drops being mostly ignorable unless they're a big upgrade
- players thinking of their background's starter kit as their "class", and constricting their gameplay & items to match it
- a certain lack of the roguelike feeling that is achieved in other roguelikes: that you are in the dungeon with nary but a dagger and a prayer, using your wits and anything you can find just to survive.

To shift things a bit closer to the thrill level of Rogue, and to speed up game start by reducing/removing `WCHOICE_X`, i suggest that servers host an experimental branch that significantly nerfs backgrounds.  This might also help newer players learn faster that Species and Deity are much bigger decisions than Background.

(As an example, [my branch](https://github.com/RojjaCebolla/crawl/tree/whimsFloorGod) removes 1 spell from all book starts, downgrades all armour, and downgrades all weapon choices.  It might also be nice to make SK_WEAPON simply grant skill in **all** weapons, so that switching to a floor drop is more enticing.  Tried it a couple times, still seems playable!)

**Comment by ByrelMitchell** [comment]
Overall, I think this might be fun; if there's an experimental I look forward to trying it and seeing.

On one of your minor points, if SK_WEAPON grants skill in all weapons might that not be too good on gnolls? They already have a rather ridiculous early game.

**Comment by Diojeanne** [comment]
I've been thinking over this, and I played a bit on your whimsFloorGod branch, and it seems to me that for most characters, in your branch as in mainline crawl, aptitudes and therefore species is your destiny. It's a BIG decision to go against your apts.  Starting skill levels (excepting gnolls, of course) are quickly washed out if you refocus your training early. But those apts will stay with you forever (excepting when you find a manual.) Check out the attached chart 
![image](https://user-images.githubusercontent.com/12580216/88332441-6d342d80-cce3-11ea-96ee-757c640c4d3b.png)
(due to maniacjoe.) It relates to shields skill but training scales the same for other skills. From an optimality perspective, your gear choices are made before a WCHOICE function is ever called. For species with even apts, background has a slightly bigger impact particularly early on, but if you really want people considering every item on the floor, apts have to be scaled down or removed.

I think granting weapon skill in all weapons is not a great solution to any problem: for one thing is makes the skills screen a mess. It also makes very little thematic sense. Better in my opinion to buff weapon effectiveness at zero skill and remove weapon skill from most backgrounds (I guess fighters, gladiators, hunters, arcane marksmen, and mayber berserkers could still start with weapon skills.) For a general "improve any weapon's starting prospects" skill, fighting is right there, and increasing your accuracy truly matters in the early game.

Nerfing the starting gear DOES encourage wear-IDing floor items, but still really only within your species destiny. A merfolk MIGHT try out an early artifact short blade, but otherwise they should really stick with polearms.

As for the starting book nerf, it goes both too far and not far enough, in my estimation. I do not have to think hard to remember the last time I didn't find a spell book until late in lair, and also for most starting books four spells will still carry you through Lair. Going beyond your background for a book start is often just not achievable until Orc:2 or later. Maybe give starting books 3 spells but also guarantee a book shop between D:7 and D:10, or just increase the pop rate for books in general knowing that your starting book requires earlier supplementation. Then again, there's always Sif, Vehumet, Kiku, and Gozag if you're worried about finding spells.

**Comment by RojjaCebolla** [comment]
> forces me to choose a caster god

I think a lotta folks forget that, one option for a book start is to learn higher level spells, but another option is to train up and cast your starter spells in heavier armor.  you can burly your way through things until a great weapon or further spells drop!

sorry to not respond to the rest of your thoughts (yet), but i did read them!  this was the easier part to reply to quickly.

**Comment by Diojeanne** [comment]
> I think a lotta folks forget that, one option for a book start is to learn higher level spells, but another option is to train up and cast your starter spells in heavier armor. 

True, and on a long enough timeline (extended/zig) most characters will wind up casting powerful magic in heavy armor anyway, but the utility of early hybridization is quite limited without favorable apts, and once again that's running into the species destiny issue. Background is just already far more mutable than species. I'm not saying remove apts instead, (though I'd be heartily in favor of making them less severely impactful across the board) and I like the idea of weakening most starting kits to make early weapons and armor more interesting... but you're going to find plate mail by lair and wights will offer some kind of good weapon. Books are just rarer. Nerfing book starts makes any books you find that much more precious, but fairly often your first book will be found in Lair or in a shop on Orc:2. Whether that's intrinsically too late or not, it doesn't go toward  your stated goal of making early treasure more interesting to consider.

**Comment by ebering** [comment]
I think this conversation has served its purpose as far as driving crawl development. In 0.27 most of the mage backgrounds lose a high level spell (we didn't quite get to all of them) in 9e18931815c . Curses were also removed outright, so some of the considerations of this discussion (pressure to use dangerous items in the early game) would need to be re-visited. I don't think there's as much of an appetite for reducing the starting non-book item quality.

Thanks everyone who shared their thoughts!
