### ISSUE TITLE
Gold not generating properly - Megazig - Elf level

### ISSUE THREAD

**Issue by shummie** [crawl/crawl#1495]
CKO Webtiles - 0.25.0-9-g26727b657a

I've noticed, but haven't documented until now, that gozag gold doesn't generate sometimes in Elf megazig levels. Often this is on larger zig levels, in this specific case, Zig level 20.

Attached is an example of what is happening:

![0 - initial state](https://user-images.githubusercontent.com/3296707/88437831-f3786e80-cdcc-11ea-899e-bcd3197b3476.JPG)
The above is the initial state. You can see that there is a bunch of spaces that don't have gold but equipment.
![1- initial gold](https://user-images.githubusercontent.com/3296707/88437860-08550200-cdcd-11ea-867d-703d91ea5e85.JPG)
Doing a Ctrl-F on this initial state shows that there are 309 instances of gold pieces on the floor.

![2 - After ignition](https://user-images.githubusercontent.com/3296707/88437920-27ec2a80-cdcd-11ea-965a-fdf2c975d6e4.JPG)
Casting ignition on this floor and killing a bunch of elves do not seem to generate gold.
![3 - new gold](https://user-images.githubusercontent.com/3296707/88437950-35a1b000-cdcd-11ea-9dec-deb9eef13387.JPG)
Another Ctrl-F shows that there are now only 5 more stacks of gold over the prior state.

**Comment by rawlins** [comment]
I haven't tried to replicate this yet, but my first-pass guess is that these megazig levels, because their inhabitants also have a lot of items, are simply hitting the per-level item limit (in which case no more items will generate).

**Comment by rawlins** [comment]
I still haven't replicated this after some trying, so a save backup might be useful, but from my testing I think my initial theory above is still plausible.  The item max is 4000 items per level, and I was easily able to get a medium depth megazig elf level (just based on a testing char I had sitting around) to generate around 2000 items including gozag gold, so doubling that at the megazig maxes seems like it could happen. Lots of ammo sitting around would help. I think there are either two outcomes: this gets marked as wontfix because increasing the item limit to account for such an unusual situation is too wasteful, or the item limit gets slightly bumped to accommodate these extremes. But I would want to replicate it or look at a save before making a decision, in case there is something else going on, and it would help knowing what the item limit needs to be for this situation.

**Comment by shummie** [comment]
Sorry for the delay, attached is a link to a state which duplicates the issue (I hope)

http://crawl.kelbi.org/saves/shummie-crawl-0.25-200905-2001.tar.bz2

**Comment by rawlins** [comment]
This is indeed case of hitting `MAX_ITEMS`. I think what is pushing it over the edge is that this is an elf floor with a lot of arrow piles accumulating, along with everything else you hit on zig 27 + the gold piles. My inclination is to not change anything, because increasing the item limit produces a major save incompatibility, and this is a very unusual case. But I'll leave this open for now in case there are other opinions.

**Comment by semitonal** [comment]
Closing - as noted above, this is an extreme case that isn't worth fixing, and is probably also less likely to happen now anyway with ammo no longer dropping.
