### ISSUE TITLE
OBJ_MISSILES that are launcher ammo get mulched when thown 

### ISSUE THREAD

**Issue by Rytisgit** [crawl/crawl#1505]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION:**
trunk

**DESCRIPTION:**
thrown OBJ_MISSILES that are launcher ammo, get mulched. https://github.com/crawl/crawl/blob/faca0e1de59ac90511a73b61e46c10dafe02a932/crawl-ref/source/throw.cc#L1197 since launcher ammo has a mulch rate it gets destroyed by this function

**Comment by Diojeanne** [comment]
Is this not the intended, or at least acceptable (since I doubt anyone ever specifically considered it in development) behavior?  Throwing an arrow seems like something you'd want to avoid if you were especially concerned to keep the arrow in usable condition. And it mulches at the usual rate, not 100% or anything.

**Comment by Rytisgit** [comment]
Sure, its very possible to keep it as is, I'm just highlighting and letting others decide, it doesn't impact me too much. Except that the objmissiles are intended to be destroyed as they do damage, and launcher ammo doesn't when thrown clumsily.
