### ISSUE TITLE
Vault Wardens locking me out of the room they're in

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#1534]
**PLATFORM and OS or BROWSER:**
Webtiles 0.26-a0-591-g04f19ec on cbro in Firefox 79
**DESCRIPTION:**
In Vaults the Vault Wardens are pushing me to the wrong side of the door when using Seal Doors. This has only happened to me when using Yred so it might have to do with that.

**EXTRA FILES:**
![image](https://user-images.githubusercontent.com/70080435/91110732-b2ce7800-e64c-11ea-9949-c7497d262668.png)

**Comment by rawlins** [comment]
Some digging: There's not actually any connectivity check, what it does is see how much tension would be lowered by closing the door, and close it if it wouldn't be lowered too much.  So I suspect what is happening here is that the presence of so many allies is really throwing tension off, meaning it's low or even 0 before the door closes. In that case, it would be impossible for closing the door to lower tension relative to the baseline.

Not immediately sure what the best fix is, in some cases including allies in this calculation is correct (so that a warden can cut you off from them). One idea might be to do two checks, with and without allies, and fail if either lowers the tension too much.

Past reports:
https://crawl.develz.org/mantis/view.php?id=8085
https://crawl.develz.org/mantis/view.php?id=10542
