### ISSUE TITLE
Collected rune not appearing on runes collected screen

### ISSUE THREAD

**Issue by particleface** [crawl/crawl#1606]
webtiles trunk on firefox
version: 0.26-a0-784-g51bffae0b1

Collected the barnacled rune of zot and checked the } rune page. It says that I've collected 1 rune but the line of text that listed the barnacled rune of zot is not present.

![image](https://user-images.githubusercontent.com/74208808/98586111-3e43c680-2296-11eb-842f-fc92ee95fc79.png)

https://crawl.kelbi.org/crawl/morgue/particleface/particleface.txt

**Comment by rawlins** [comment]
Thanks for the report. It looks like the logic for this is tied to logic for [which branches can generate](https://github.com/crawl/crawl/blob/master/crawl-ref/source/dgn-overview.cc#L1085) -- and this logic is currently suspended so that people can test new-swamp more effectively (i.e. swamp always generates right now). The change is temporary but I don't know the exact plans, so I'll let @PleasingFungus decide whether it is worth fixing in the meantime. (I suspect some other dungeon overview stuff relies on this logic as well.)

**Comment by PleasingFungus** [comment]
Oh, ha. I'll take a shot at fixing it.

**Comment by PleasingFungus** [comment]
Should be fixed in 1f3e2359fbfb035a6697a46dd7d330b6797f5d34 . Thanks for reporting!
