### ISSUE TITLE
Password Reset Webtiles

### ISSUE THREAD

**Issue by levlazarev** [crawl/crawl#1619]
**PLATFORM and OS or BROWSER:**
WebTiles

**DCSS VERSION:**
0.25

**DESCRIPTION:**
Trying to reset/change password for my WebTiles account
User: Leviel
Email: mabushii.naito@gmail.com
URL: https://cbro.berotato.org/

**Comment by rawlins** [comment]
Sorry to miss this earlier (we don't usually get pw reset requests through issues, though it makes perfect sense why you'd try it), do you still need a CBR2 password reset?

**Comment by levlazarev** [comment]
Yes please, sorry about that I couldn't figure out where to send the
request.

**Comment by rawlins** [comment]
Did this get sorted? I did send a password reset message to the email on file (same as here) at some point back in December.

**Comment by levlazarev** [comment]
I dont recall receiving it so it may have missed it. If you could send
another I would appreciate it.

**Comment by rawlins** [comment]
I'm going to close this up, several attempts at coordinating didn't really work and I think the project issue tracker is not the right place for password reset requests because we don't use it for rapid communication. @levlazarev (or others), if you would like a password reset on CAO, please feel free to ping me on discord (as `@advil` in the roguelikes discord) or via email (email in my github profile or to `advil at dcss.io`). Sorry about this.

**Comment by levlazarev** [comment]
Okay thanks for letting me know
