### ISSUE TITLE
Potential issue with wand of digging not respecting FTILE in vaults

### ISSUE THREAD

**Issue by pdpol** [crawl/crawl#1628]
**PLATFORM and OS or BROWSER:**
local tiles on OS X high sierra

**DCSS VERSION:**
0.26-a0-1005-g7af7f965e9
Compiled from master branch

**DESCRIPTION:**
Could just be unexpected behavior due to me not knowing enough about vault .des syntax.

I was messing around with [zin_treasury](https://github.com/crawl/crawl/blob/master/crawl-ref/source/dat/des/altar/overflow.des#L2607-L2616) in wizard mode and noticed that when I zapped an iron grate with a wand of digging, instead of the `floor_limestone` tile I thought would show up it was a `floor_grey_dirt` in the fashion of the rest of the dungeon floor.

I thought because of [this section](https://github.com/crawl/crawl/blob/master/crawl-ref/docs/develop/levels/syntax.txt#L1109-L1111) of syntax.txt that FTILE is used after the destruction of the grate.
```
KFEAT:  m = iron_grate
FTILE:  _.m+$ = floor_limestone
```

**EXTRA FILES:**
<img width="819" alt="Screen Shot 2020-12-06 at 1 06 11 PM" src="https://user-images.githubusercontent.com/1066352/101290315-60fec780-37cf-11eb-8cbd-101bd2b7f1fb.png">

**Comment by DreamDustDCSS** [comment]
I've also noticed this pretty frequently and with more than just this particular vault. It seems a vault's FTILE isn't preserved (definitely used to be at one point, I remember!) when a wall is destroyed. Instead the tile becomes the default DNGN_FLOOR for whatever branch/floor you're on.

I'm not a dev (or even a programmer), but I wanted to share what I found with my clumsy code-diving:
Digging, Shatter, and Overgrow all call a "destroy_wall" function, so I suspect the problem lies there. You can find this function [here](https://github.com/crawl/crawl/blob/master/crawl-ref/source/terrain.cc) (terrain.cc).
Suspicious excerpt:
`_revert_terrain_to(p,
            env.grid(p) == DNGN_MANGROVE ? DNGN_SHALLOW_WATER : DNGN_FLOOR);`
Browsing through some past commits, this one caught my eye - https://github.com/crawl/crawl/commit/ef970caa618cb9f89bca8ef4e72e7939b08232c1
_"Always clear tile flavour when destroying walls"_
To be fair, I have no idea if this commit is what caused the problem... but it's a possibility? Hopefully an actual dev takes a look eventually. Although I figure this is (rightfully) a very low-priority issue.

**Comment by DreamDustDCSS** [comment]
Oh wow, that was actually the problem! 
I just edited terrain.cc on my local version of Crawl to revert https://github.com/crawl/crawl/commit/ef970caa618cb9f89bca8ef4e72e7939b08232c1, rebuilt Crawl, and tried digging to see if that would fix it. And it did!

Before (tested on the zin_treasury vault, but again - this seems to affect all vaults):
![image](https://user-images.githubusercontent.com/83979029/135716004-cab4da34-7a6b-48ef-9c63-8456664dbaa7.png)

After:
![image](https://user-images.githubusercontent.com/83979029/135716024-52ea2663-db82-40a2-86ad-caf4e6e12a2a.png)

**Comment by DreamDustDCSS** [comment]
The only problem (probably) with reverting this commit is that it was originally done to fix some other obscure bug (see: [here](https://crawl.develz.org/mantis/view.php?id=12053)) involving Jorgrun digging terrain in Swamp. So that bug might come back if we revert the commit. Hmm...
