### ISSUE TITLE
eye of draining infinite drain loop

### ISSUE THREAD

**Issue by sokol815** [crawl/crawl#1651]
**PLATFORM and OS or BROWSER:**
Webtiles, Windows 10 Chrome on cbro.berotato.org git branch

**DCSS VERSION AND GAME INFORMATION:**
Playing on DCSS trunk from 12/20/2020 username: sokol815

**DESCRIPTION:**
Currently running in a ziggurat with an Octopode. Ran across 2 separate eyes of draining each trapped behind iron grates. I keep getting messages that the eye of draining drains my mana, then the more prompt... no opportunity to react or move away or anything. On the first one, I just held down enter for 5 or 10 seconds... but realized it wasn't leaving the loop. Currently on the 2nd eye of draining... I thought the 1st one drained me for a few times, then I just reloaded the page... I think it might have been about 10000 auts worth of turns. After reloading during the 2nd lockup, the eye of draining seems to have drained me for about another 50 to 100 auts. I did not hold down enter at all on the 2nd eye before refreshing the page. The timer does not update on the page between each more prompt.
https://i.imgur.com/rhSdsMc.png

Reloading does appear to break the infinite loop somehow.

I just did a save export and confirmed I appear to have been on level 17 of this ziggurat for over 13,000 auts... which seems absolutely insane. Probably about to die due to zot timer. 
https://pastebin.com/gR3AgBui

**EXTRA FILES:**
I'm currently using HilariousDeathArtist's RC: https://github.com/HilariousDeathArtist/DCSSConfigFile/blob/master/HilariousDeathArtist.txt

cbro does not appear to accept my same user's username/password for ssh connection, so I could not create a save backup.

**Comment by rawlins** [comment]
Thanks for the report! I was able to replicate this by autotraveling into the los of a trapped draining eye. It does not seem that the HDA rc file is the issue here, except that it adds a force_more for the draining message, making the loop harder to break out of (in a regular game you can hit a key to stop it).

> cbro does not appear to accept my same user's username/password for ssh connection, so I could not create a save backup.

For future reference (looks like this game is over), you first log in to ssh using a generic login, which in this case uses username `crawler` and requires an ssh key instead of a password; see http://crawl.develz.org/wordpress/howto for more info. After this login you then use your regular username/password at the menu.

**Comment by sokol815** [comment]
Thanks for your reply. Glad it was easy reproduce, I'm used to it being much more difficult; so that's a pleasant surprise. I'll remember this information for next time.
