### ISSUE TITLE
Damnation casters not respecting other monsters

### ISSUE THREAD

**Issue by MinticePIU** [crawl/crawl#1678]
**PLATFORM and OS or BROWSER:**
local tiles, Windows 10

**DCSS VERSION AND GAME INFORMATION:**
 0.26-b1-44-g1a24ab4

**DESCRIPTION:**
Damnation casters (hellions, brimstone fiends, hell sentinels...) damnate regardless of monsters nearby. It used to "respect" other monsters' HDs in 0.25 or older, but it doesn't seem to be the case in the newest patch. Seems like a bug.
`always possible there's a bug, but no intentional change to it I'm aware of; it's possible to get unlucky as there is randomness to it` - gammafunk
Posting two screenshots to show that they do damnate.
![image](https://user-images.githubusercontent.com/58921073/104133700-8b443600-53c8-11eb-9303-5506b2f28323.png)
![image](https://user-images.githubusercontent.com/58921073/104133793-2a692d80-53c9-11eb-9822-974c17bc9fc2.png)

**Comment by ebering** [comment]
Thanks for the report, this is indeed a bug and not just demons being rude.

This was inadvertently introduced in 2f2a4d8ed992e13 which refactored CALL_DOWN_DAMNATION into a zap, but in doing so no longer failed to set the explosion size for the tracer. I've pushed a fix to master, but because of how
