### ISSUE TITLE
Item List Scrolling Locked

### ISSUE THREAD

**Issue by Etainz** [crawl/crawl#1679]
**PLATFORM and OS or BROWSER:**
Webtiles - Firefox 84.0.2

**DCSS VERSION AND GAME INFORMATION:**
0.26 Arizona server (crawl.akrasiac.org)
Ongoing character (Etain) 

**DESCRIPTION:**
Issue - After scrolling down through an item menu at specific points it will no longer allow me to scroll back up. 

For example after searching the current floor's items I can scroll up/down just fine as long as I don't scroll down far enough for item "o" or "p" to be at the top of the list. Once doing that I can keep scrolling down, but when scrolling back up I can't go higher than either of those at the top of the list.

Happens with inventory menu as well. Specifically 4 different breakpoints in my current dump.  The "Jewellery" header, the "N" item (which right below the header in-game), the "T" wand and the "W" wand.

Changing the item letters doesn't help, nor does dropping them (even with all accessories dropped it'll still "lock" where Jewellery would be in the list. The break doesn't seem to be item dependent, it's based on where that item is in the list. Adding/removing/order changes don't seem to impact it, it'll "stick" in the same spot regardless.

This happens 100% of the time when going through these menus and has happened on several characters (though I haven't been testing if it's in the same spot each time).

**EXTRA FILES:**
 http://crawl.akrasiac.org/rawdata/Etain/Etain.txt

http://crawl.akrasiac.org/saves/Etain-crawl-0.26-210110-1742.tar.bz2

**Comment by ebering** [comment]
I can't replicate the "lock" behavior in current trunk; however @rawlins has been doing some recent work on scroll cursors. 

What occurs in 0.28-a0-1701-ga2763057c1 on Safari 15 is the following which seems similar to what you are describing:

1. With a full inventory open the inventory menu. The browser window must be small enough to require the inventory to scroll.
2. Scroll down with arrow keys by repeatedly pressing the arrow-key (not a hold down).
3. When the cursor reaches a point where it triggers a scroll, it jumps back up several rows.
4. The row that the cursor returns to after a scroll is consistent in a single menu usage, and the same row is jumped to when scrolling back up.
5. Unfocusing the crawl tab with the menu open and then re-focusing it (which I did while writing this bug report) causes the buggy behavior to cease.

Because of 4 and 5 I suspect this is an uninitialized javascript variable problem? The cursor behaves as expected in local console.

**Comment by rawlins** [comment]
Hadn't seen this report but I believe this specific bug was fixed with b5dea8a184d5, it was an issue with the way headers were handled in scrolling up; I'm going to close it. Feel free to reopen if it recurs.

@ebering I'm pretty sure you are encountering something else, in particular, you probably have your mouse over the position that the cursor it jumps back to. There's some code that's supposed to override mouse hover via a mouseenter event when scrolling with keys, but it appears it's not working right on Safari.
