### ISSUE TITLE
Typo in prompt to confirm moving into excluded area as op

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#1825]
![image](https://user-images.githubusercontent.com/70080435/111015257-e917de80-8375-11eb-85a9-8b068111151b.png)

**Comment by shummie** [comment]
This issue is also true for Tengus, as they "Glid". This is caused by the usage of the walking verb, which is a prefix that allows -ed or -ing to be added. 

In the yaml files, there are walking verbs that are used to describe movement. The documentation states that this should be a word prefix that can add -er or -ing to describe movement, such as Glid, Wriggl, and Slither. In that context it makes sense, but there are situations where the verb itself is used, without a suffix being appended to it. This occurs in check_moveto function, where it uses the return value of species_walking_verb directly. For Naga it works, but for Octopodes and Tengus, you get the text, "Really wriggl into that cloud of blessed fire?".

There are multiple fixes i can think of, one being to add a new field to the yaml that's the base verb, which is what it is today, and then the current tense? verb which adds the e for glide and wriggle, or to rewrite the species_walking_Verb function to take an ending value ("er", "ing", etc...) but then tha twould have species specific coding in that function which probably makes it annoynig if u had to add new species and forget to do it, so maybe the frist is the way to go and then modify the functions that want the present tense vs other suffixies?

**Comment by ebering** [comment]
@shummie I like the resolution that adds two fields:

`species_walking_verb_stem` (the current field)
`species_walking_verb_present` (for the present tense)

since the alternative would be specifying various verb irregularities in the walk verb yaml. Someday we might add strange enough moving species that that work will be required, but that day is not today.

Are you planning on writing a PR? It would be appreciated!
