### ISSUE TITLE
Game Crash with: species of 4294967288 out of range 0 (0) .. NUM_SPECIES (41)

### ISSUE THREAD

**Issue by martbhell** [crawl/crawl#1850]
**PLATFORM and OS or BROWSER:**
https://underhound.eu:8080/#lobby
Windows 10 20H2
Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)

**DCSS VERSION AND GAME INFORMATION:**
 0.27-a0-737-g0a99b99

**DESCRIPTION:**
I was playing a MiFi and suddenly it crashed with this error:
```
species of 4294967288 out of range 0 (0) .. NUM_SPECIES (41)
```

Crashdump: https://underhound.eu/crawl/morgue/martbhell/crash-martbhell-20210324-172947.txt

has

ERROR in 'species.cc' at line 31: ASSERT failed: species of 4294967288 out of range 0 (0) .. NUM_SPECIES (41)

which points to https://github.com/crawl/crawl/blob/e4d627daa37096d72e63f224a142698cad0bae49/crawl-ref/source/species.cc#L31

Have not been able to reproduce it (yet). Maybe I died?

**EXTRA FILES:**
https://underhound.eu/crawl/morgue/martbhell/crash-martbhell-20210324-172947.txt
https://underhound.eu/crawl/saves/martbhell-crawl-git-c3205288ea-210324-1742.tar.bz2

**Comment by rawlins** [comment]
This (and its consequences) should be fixed by e4d627daa37096d7, f22881d5bd9, 2a0442d20d0, and 3e622ea735797.

For anyone who tried and failed to replicate this, it needed a classic Dj in the high score file. I had some saves for that species sitting around so I have been able to replicate this locally and confirm the fixes.
