### ISSUE TITLE
Ghost walking free 

### ISSUE THREAD

**Issue by Sobieck** [crawl/crawl#1944]
**PLATFORM and OS or BROWSER:**
webtiles - firefox

**DCSS VERSION AND GAME INFORMATION:**
Version history for your current game:
Game started: 0.27-a0-1137-g3ef0f4ec91
0.27-a0-1139-g28e009f8a6

**DESCRIPTION:**
I believe there might be a problem with map generation. I had a wizlab generated in what appears to be a ghost room. The ghost was just out walking around like the old days. 

![image](https://user-images.githubusercontent.com/6256765/117468678-8b89b380-af1a-11eb-894d-e12dc3afc7a5.png)

**Comment by DreamDustDCSS** [comment]
These are the two vaults:
```
NAME:       mu_enter_wizlab_4
KFEAT:      ! = floor
COLOUR:     ! = magenta
FTILE:      !O = floor_rough_magenta
:           wizlab_portal(_G)
MAP
    xxxxx
    w!!!x
   ww!O!x
  www!!!x
 www..www
www..www
ww..www
w..www
@.www
@www
ENDMAP
```
```
NAME:   ebering_vaults_ghost_xom
TAGS:   vaults_orient_s
: lone_ghost_guarded_loot(_G, "O")
: lone_ghost_extra_loot(_G, ".")
: setup_xom_dancing_weapon(_G)
KMONS:  O = player_ghost
KFEAT:  _ = altar_xom
: vaults_ghost_setup(_G)
MAP
...1...
..d_e..
...O...
xxn=nxx
.......
.......
ENDMAP
```
So it turns out that there's nothing wrong with the wizlab or the level generator. The problem is with ghost vault, which is completely open for some reason.
I can try fixing it in a PR later. Thanks for reporting!

**Comment by gammafunk** [comment]
This bug is in fact due to an interaction of the level generator and the wizlab portal vault. For Vaults branch, vaults exist as special "room vaults" that the layout loads on its own directly into the map. While the layout will never allow these rooms to overwrite each other, information about the original room vault is lost for use by any subsequent non-room vaults. In most cases such non-room vaults don't get placed at all, since the layout doesn't use them. But certain things like portal vaults can place as minivaults, since they use CHANCE.

When a minivault placement does happen, the vault can't see that it's overwriting a vault room due to how the room is loaded by the layout code. The minivault proceeds to overwrite the vault room, and this often doesn't cause any major problems. Ghost vaults are one type of room that does cause a problem, however. Vaults is extremely dense with these vault rooms, so if a minivault did try to respect not overwriting vault rooms, it would likely find difficulty placing at all.

Probably the best solution is do have Desolation/Wizlab entrances place as vaults rooms in Vaults, using a new vault room tag and with modifications to the portal vaults to allow them to function as rooms. That would also require some modifications to Vaults layout similar to what was done for ghost vaults. It's not particularly good to have minivaults clobbering vault rooms even if they aren't ghost vaults. Outside of some major rework of the vaults layout, it's probably best to have all vaults that would place in Vaults branch use the room system.
