### ISSUE TITLE
Inaccessible altar vault

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#1981]
**PLATFORM and OS or BROWSER:**
webtiles trunk 0.27-a0-1256-gced786f65e

**DESCRIPTION:**
Inaccessible altar vault generated on elf 3. Game is still ongoing so I will post the morgue when its over

![image](https://user-images.githubusercontent.com/70080435/121625167-f1e58280-ca40-11eb-89c1-8bb9d5618692.png)

**Comment by ardl** [comment]
Morgue
https://cbro.berotato.org/morgue/ardl/morgue-ardl-20210612-211307.txt

**Comment by DreamDustDCSS** [comment]
> NAME:   lemuel_upstairs_altar
TAGS:   extra
DEPTH:  Elf, Crypt
ORIENT: float
SUBST:  T:T., )=)}], c:ccx
KMASK:  T = no_monster_gen
MAP
ccccccc
cT...Tc
c.....ccccccc
c..C..+....)c
c.....ccccccc
cT...Tc
ccccccc
ENDMAP

This vault is supposed to have a downstair - } ) ] - in that top corridor part. The idea being that you can only access this altar by taking an upstair from the floor below. 
But since the vault generated on Elf:3, there's obviously no lower floor, which should be the cause of the issue.
I think changing the DEPTH line to "DEPTH: Elf, !Elf:$, Crypt, !Crypt:$" should fix it.

If a dev doesn't fix it, I'll open a PR sometime later. I'm just a little hesitant since something in the documentation caught my eye:

> }{ - Stone stairs - You must be able to reach these from each other. The { upstair is also the stair on which the player will enter the dungeon for arrival vaults. 
)( - Stone stairs, set 2. 
][ - Stone stairs, set 3 - minivaults often fail to get this pair if the level isn't very interconnected or if any larger vaults are using      any stairs.

It sounds to me that this vault using ] is potentially a bad idea. Not sure though.
