### ISSUE TITLE
Feature Request:  Give two-handed weapons a small amount of SH

### ISSUE THREAD

**Issue by DreamDustDCSS** [crawl/crawl#1991]
I feel (and it seems to be a popular sentiment) that using two-handed weapons is often strictly worse than using a one-handed weapon along with a shield. 

The extra survivability you get from a shield is just too good to pass up, and sometimes two-handed weapons don't even feel better than one-handed weapons (compare a great sword to a demon blade, for example).

I propose that we give two-handed weapons a _small_ amount of SH to help balance this. I think it makes sense too, since shouldn't a large polearm or giant sword be able to block some attacks for you?

The amount of SH is up for debate, but I was thinking we could give two-handed weapons either [1] a flat/static amount (+5 SH?) or [2] a variable amount that scales with weapon skill (+2 at 0 skill, up to +8 at 27 skill?).

I personally like the idea of option 2, since it makes sense that as you become more skilled with a weapon, the better you are at using it to block attacks. But it's also more complicated than just adding a flat/static SH bonus to every two-handed weapon.

Thoughts?

**Comment by rawlins** [comment]
If two-handed weapons needed a buff (or one-handed weapons needed a nerf, i.e. a relative buff for two-handed weapons), there are a lot of knobs to tweak, I'm not sure that adding SH for 2-handed weapons would be my first choice. Probably either just skill cost or weapon delay. In fact some tweaks of this kind have happened in the recent past, see e.g. 2393aa77 for a detailed discussion.

For what it's worth, the meta about shields has drastically flip-flopped since I've been a dcss player who is skilled enough to win regularly, so I don't think looking at the current meta gets entirely trustworthy answers about things like "optimal" or "strictly worse". Also for what it's worth, I do actually tend to prefer shield chars myself these days but for me that's largely about skill cost, and also about the kinds of characters I play.

**Comment by DreamDustDCSS** [comment]
I forgot about the recent-ish tweaks to broad axe delay and shield penalties. Those are good points to bring up.

And yeah, that's really at the heart of the topic. "_Why would I want to use a battleaxe when I could use a broad axe + shield instead?_" Ditto for the other melee weapon types. 
I feel like most people only use two-handed melee weapons if they find an amazing artefact one relatively early in a run. A separate but probably related issue is the kinda extreme rarity of executioner's axes, triple swords, etc. At least for basic 3-rune runs, you only have a decent chance of finding one in the Hall of Blades, and it isn't even guaranteed. This unreliability makes 1h+shield even more appealing in comparison. And even if you _do_ find an awesome 2h melee weapon you'd like to use in the Hall of Blades, by that point you've probably already invested into the Shields skill and are reluctant to give up on it.

But as you said, this perception (which is the meta AFAIK and also my own personal bias) could be mistaken.

**Comment by kuniqsX** [comment]
The old, flat&constant +5AC prot. brand bonus was abused as a free weapon-slot =oProtection. Bucklers would be of little use if a great sword gave a flat +5SH and a free 15-damage riposte attack to boot, especially when you consider how rare shield brands are.

18 Axes + 15 Shields training for a broad axe + kite shield costs 28% more (skill point-wise, total cost with 0 aptitude) than just 20 Axes for a battle axe. 14 Long Blades + 15 Shields for a demon blade + kite shield costs pretty much as much the same as 20 Long Blades for a great sword. You could train one skill to 22 instead of one to 18 and other to 15.

Unless you're a large race with less Shield skill requirements, or a fragile race with restricted slots, or a pure caster, or you found a good (un)randart/branded shield (and those spawn in maybe 1 in 3 games) it's just not optimal to train the Shield skill.

For a melee build it's best to ignore shields and fight with 1H weapon until you build enough skill to counter the swing delay and accuracy penalty.

**Comment by ebering** [comment]
Closing this in light of  2393aa7 and related commits.
