### ISSUE TITLE
Fedhas' Overgrow doens't show highlighted tiles +@

### ISSUE THREAD

**Issue by dillytin** [crawl/crawl#2018]
0.27-a0-1442-g87b6fcb595,

1.

![캡처2](https://user-images.githubusercontent.com/65288602/124762184-976f1180-df6d-11eb-9869-7104b3a50408.PNG)

It used to show highlighted walls in yellow when they are affected by Overgrow but now it seems it doesn't.

2.

You can fail to use Overgrow before you select the wall(the moment you use the ability). I'm not sure it is intended or not. For example, Qaz's Upheaval fails AFTER you select a target. However, Beogh's Smiting fails BEFORE selecting a target. I don't know which one is intended.

**Comment by gammafunk** [comment]
I fixed (1) and part of (2) in the above commits. For (2), the way Qaz' Uphheaval works is (I think) the correct way these abilities should work. You should be able to see what you might affect with the targeters of targeted abilities without triggering any failure chance, since the targeter helps to decide whether using the ability is worthwhile. Fedhas' Overgrow now works this way, as already did the other targeted Fedhas abilities.

Beogh's Smite ability is a trickier case because of how it uses the spell system code, namely it calls `your_spells()`. I'm not sure if we should extend `your_spells()` in some way to allow the idea of post-targeting failure. Seems it wouldn't be terribly difficult as it already returns an `spret` value. It's possible @rawlins has insight on this general issue in terms of UI and/or implementation.

**Comment by ebering** [comment]
The Beogh issue was fixed in b3aea5d0147 which addressed several such sequencing issues.
