### ISSUE TITLE
Autoexplore no longer stops when new items are found

### ISSUE THREAD

**Issue by nicooo** [crawl/crawl#2026]
**PLATFORM and OS or BROWSER:**
local tiles
arch linux 5.12.15-1-ck-zen

**DCSS VERSION AND GAME INFORMATION:**
0.27-a0-1545-g3eddc1d3d3

**DESCRIPTION:**
Pressing 'o', the game used to stop when a new item, shop or stairs came into view. Now it only stops when a monster comes into view or after picking up an item.
not working commit 3eddc1d3d3a17b45feb7f5c5e78d038979435fd9
working commit 1e82c303ef7d44d67a0d25ec1dc29485a3bd925b

**EXTRA FILES:**
[init.txt](https://github.com/crawl/crawl/files/6804369/init.txt)

**Comment by ebering** [comment]
I was able to bisect this before calling it an evening. @Aliscans this was introduced by 09c7552f2226 (your PR #1936 ) and I know you've worked on travel code some recently, so perhaps you know a quick way to fix it. Otherwise I'll try to take a look tomorrow (in the meant time if someone wants to revert feel free).

**Comment by rawlins** [comment]
This was fixed in the referenced revert commit, though someone should eventually figure out how to restore the feature.
