### ISSUE TITLE
Just a few compiler warnings...

### ISSUE THREAD

**Issue by jv84** [crawl/crawl#2031]
levcomp.ypp:40.1-7: warning: POSIX Yacc does not support %expect [-Wyacc]
   40 | %expect 2
      | ^~~~~~~

initfile.cc: In function 'std::string find_crawlrc()':
initfile.cc:1688:28: warning: loop variable 'rc_fn' of type 'const string&' {aka 'const std::__cxx11::basic_string<char>&'} binds to a temporary constructed from type 'const char*' [-Wrange-loop-construct]
 1688 |         for (const string &rc_fn : rc_dir_filenames)
      |                            ^~~~~
initfile.cc:1688:28: note: use non-reference type 'const string' {aka 'const std::__cxx11::basic_string<char>'} to make the copy explicit or 'const char* const&' to prevent copying

**Comment by jv84** [comment]
I assume libpng warnings can't be fixed. And why Perl fails to set locale?

**Comment by jv84** [comment]
From util/Makefile change "bison -y" to "bison -Wno-yacc". That quiets the other warning.

**Comment by rawlins** [comment]
Stock `bison` on OS X, even current big sur, is bison 2.3, which unfortunately doesn't support `-W`. Possibly just dropping `-y` would be enough to fix this warning, but dropping `-y` also would need some testing.

**Comment by jv84** [comment]
> Stock `bison` on OS X, even current big sur, is bison 2.3, which unfortunately doesn't support `-W`. Possibly just dropping `-y` would be enough to fix this warning, but dropping `-y` also would need some testing.

Or choosing the flag depending on which version is detected?

Still about those libpng warnings... I understood they appear because png files are saved with some incompatible metadata.
Is this the case?

**Comment by jv84** [comment]
I don't use macOS but it seems that a newer version of bison can be installed with Homebrew.

**Comment by jv84** [comment]
I'm suggesting to fix png files with this command:

`find -name *.png -exec mogrify -interlace none -strip '{}' +`

**Comment by rawlins** [comment]
> Does it have to be supported?

Yes; adding additional deps is not remotely worth getting rid of a harmless warning that appears on some platforms.

> I understood they appear because png files are saved with some incompatible metadata.

For previous discussion of libpng warnings, see https://github.com/crawl/crawl/issues/1710 and https://github.com/crawl/crawl/pull/1727. I don't think we are likely to fix these in the repository -- it would increase the repository size (substantially) for no real reason. The warnings are completely, 100%, harmless for our purposes.

In general, fixing dep-related warnings like those in this thread is very low priority -- we will deal with them if we can (as illustrated by my commit early on), but there isn't urgency. I haven't closed this thread because I suspect the bison warning is fixable, but if you would like to see it fixed, a PR that is tested across platforms is what would be needed rather than additional commentary.

Also, we receive emails every time someone posts anything on github, there is no need to additionally flag it in `#crawl-dev`. If you would like to participate in `#crawl-dev`, please don't treat it as a place for drive-by comments; I think every time someone has tried to respond to you there you'd already left the channel.

**Comment by rawlins** [comment]
The initfile.cc warning is fixed, and the bison/yacc one isn't; I think I'm going to close this as wontfix, though if someone does want to do the testing to fix it (in a safely cross-platform way, without adding deps) we'd probably accept the PR.
