### ISSUE TITLE
Nonexistent spell

### ISSUE THREAD

**Issue by jv84** [crawl/crawl#2044]
There's a nonexistent spell in monster's description. I can upload the savefile if needed.

**Comment by semitonal** [comment]
If you can upload a screenshot, savefile or any additional details of which monster was affected that would make it possible to confirm if there's a bug occuring, but most likely this is the expected result of a monster having a spell removed after a save transfer.

**Comment by jv84** [comment]
I opened the savefile again and the spell doesn't appear anymore.

**Comment by ebering** [comment]
Save transfer means the process of upgrading a save generated from an old version of crawl to a new one. If you pull regularly from git, every time you load a save from an older compile crawl performs this transfer. Since the spell is removed now the removed-spell-cleanup-code appears to be working.
