### ISSUE TITLE
Attacking with !a on "a" and "b" weapons means you keep on swapping

### ISSUE THREAD

**Issue by Aliscans** [crawl/crawl#2057]
**PLATFORM and OS or BROWSER:**
Linux 3.16.0 console using XTerm(358)

**DCSS VERSION AND GAME INFORMATION:**
Dungeon Crawl Stone Soup 0.28-a0-102-g63c4f9efeb

**DESCRIPTION:**
If I'm wielding a melee weapon in slot **a**, have another in slot **b**, have inscribed both weapons with **!a**, and try to attack a monster, the game spends a turn swapping to slot **b**.

If I try to attack again, the game spends another turn swapping back to slot **a**.

I would expect to see a "Really attack" message instead, but I only get that if the second weapon is something nasty like a weapon of distortion (in which case the game asks about both weapons). 

Should _autoswitch_to_melee() call needs_handle_warning() on both weapons?

**EXTRA FILES:**
[Trapped.cs.gz](https://github.com/crawl/crawl/files/6962578/Trapped.cs.gz) : A (sprint) saved game which exhibits this problem.

**Comment by rawlins** [comment]
I can only replicate this with `auto_switch = true`, which is not the default setting. I think this is basically expected behavior with that option in this scenario, though a possible tweak as you say would be to check `needs_handle_warning` before switching. However, because this option is not the default I'm less inclined to protect the player from their inscription mistakes, because I think that would lead to even more special cases.

With `auto_switch = false` you do get a "really attack?" prompt.

**Comment by Aliscans** [comment]
Sorry, I forgot to check what happened with default settings. And thanks for the fix.

The character I'd noticed this with was wielding two staves I'd inscribed with !a when I still had a melee weapon. There was a plant in my way, and it didn't seem worth a fireball. Thanks again.
