### ISSUE TITLE
INSTALL.md broken link in the advanced/code coverage section

### ISSUE THREAD

**Issue by Aarrn33** [crawl/crawl#2108]
The INSTALL.md file in the crawl-red folder has a broken link on the advanced/Code Coverage section.
The link is supposed to send the user to a testing.md file but I can’t seem to find. I would think that the file was deleted in an older version. 
I would think you that the link or the entire Code Coverage section might need to be removed.

**Comment by lukem12345** [comment]
I checked the raw view of INSTALL.md. I believe the testing.md file that you are looking for is located at crawl-ref/docs/develop/testing.md.
The link to this file is broken in INSTALL.md as you noted: [testing.md](crawl-ref/docs/develop/testing.md). Since INSTALL.md is in the crawl-ref directory already, the use of “crawl-ref” in the included path is incorrectly expanded to crawl-ref/crawl-ref/docs/develop/testing.md. The correct link would be [testing.md](docs/develop/testing.md). What likely happened is that INSTALL.md used to sit outside of the crawl-ref directory like README.md and SECURITY.md, but was eventually moved into this directory without updating that link.

While on the topic of broken links, I believe the link to tilegen is also incorrectly formatted. The link for it is given in plaintext as “tilegen (https://msdn.microsoft.com/en-us/library/abx4dbyh.aspx)”. I believe that there are missing brackets around tilegen in INSTALL.md.
