### ISSUE TITLE
cant find info on how to change keyboard mappings when compiling

### ISSUE THREAD

**Issue by fosBHY** [crawl/crawl#2152]
Hello there. I followed the install.md and compiling worked great. however im on a german keyboard and want to map Y to Z. Did search issues and docs for the info on how to change keymapping. i changed all y > z, Y > Z, Z > Y, z>y in docs/keybind.txt. this did not help so far. Probably the info is somewhere already as I cant imagine other users won't remap these keys, however the issue is for not having it accessible in faq, docs, ...

Thanks for your help and the game :)

**Comment by randomMesh** [comment]
I use a german keyboard too and there is no need to remap any keys. Y is Y and so on.
I guess you are using the wrong locale?

I assume you are using Linux: What does `locale` output?

**Comment by fosBHY** [comment]
> I use a german keyboard too and there is no need to remap any keys. Y is Y and so on.
> I guess you are using a wrong keyboard layout and / or a wrong locale?
> 
> I assume you are using Linux:
> 
> What does `locale` output?
> What does `cat /etc/default/keyboard` output?
> 

thank you for the hint.
Im using de_DE but as LANG i use en_US. maybe this is where crawl checks for layout? If so, then maybe it should rather check keyboard layout for its mapping?

```
xxx@xxxx ---  locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=
```


```
xxx@xxx ---  cat /etc/default/keyboard 
XKBMODEL="pc105"
XKBLAYOUT="de"
XKBVARIANT=""
XKBOPTIONS=""

```

**Comment by randomMesh** [comment]
> edit: `export LANG=de_DE.UTF-8` and then starting `./crawl` did not have an effect either

I believe you need to export LC_CTYPE as well.

See https://www.ibm.com/docs/en/aix/7.1?topic=locales-understanding-locale-environment-variables

**Comment by rawlins** [comment]
For documentation on keymapping and macros, see: https://github.com/crawl/crawl/blob/master/crawl-ref/docs/macros_guide.txt and relevant options in https://github.com/crawl/crawl/blob/master/crawl-ref/docs/options_guide.txt

Clarification question, though: is it that because `y` and `z` are swapped related to a us keyboard that you want to make the key in the `z` position on a German keyboard act like `y` for vikey navigation? Or something different than that? (@randomMesh 's answers apply if the wrong key is getting output altogether, but I can't figure out if that's really what's happening.) If that's the goal than you almost certainly want a few simple macros in your rc file like:

```
macros += M y z
macros += M z y
```

You could also use the `bindkey` option to directly bind movement and cast, using the command names from keybind.txt.

(`docs/keybind.txt` is just a documentation file. To change behavior at compile time you'd need to edit `cmd-keys.h`, but I don't think this is likely what you want.)

**Comment by fosBHY** [comment]
> > edit: `export LANG=de_DE.UTF-8` and then starting `./crawl` did not have an effect either
> 
> I believe you need to export LC_CTYPE and LC_COLLATE as well.
> 
> See https://www.ibm.com/docs/en/aix/7.1?topic=locales-understanding-locale-environment-variables
> 
> LANG is low priority while LC_CTYPE and LC_COLLATE are high priority.

thanks for your input.

```
 export LANG=de_DE.UTF-8
 export LC_CTYPE=de_DE.UTF-8
 export LC_COLLATE=de_DE.UTF-8
 ./crawl 
```
still doesnt work

**Comment by fosBHY** [comment]
> For documentation on keymapping and macros, see: https://github.com/crawl/crawl/blob/master/crawl-ref/docs/macros_guide.txt and relevant options in https://github.com/crawl/crawl/blob/master/crawl-ref/docs/options_guide.txt
> 
> Clarification question, though: is it that because `y` and `z` are swapped related to a us keyboard that you want to make the key in the `z` position on a German keyboard act like `y` for vikey navigation? Or something different than that?

Yes. The Y key of the german keyboard layout is at the position iof the Z key  of the english one and I want to use vikey navigation 

> (@randomMesh 's answers apply if the wrong key is getting output altogether, but I can't figure out if that's really what's happening.) If that's the goal than you almost certainly want a few simple macros in your rc file like:
> 
> ```
> macros += M y z
> macros += M z y
> ```
> 

as I'm "just your average user" and not used to compiling I dont really get where to put this suggested line of code. I tried it in `../settings/macro.txt` ( when assuming I'm still in the `crawl-ref` directory after following the instruction to compile ) but had to create this file myself. in `crawl-ref` itself there are some macro.* files, but none of them seem to be the place to put config in.


> You could also use the `bindkey` option to directly bind movement and cast, using the command names from keybind.txt.
> 
> (`docs/keybind.txt` is just a documentation file. To change behavior at compile time you'd need to edit `cmd-keys.h`, but I don't think this is likely what you want.)

At some point in my research I read that thats the fourth option where crawl looks for configuration

**Comment by randomMesh** [comment]
> Still interested in the "real" solution to the issue though

Then you should post more information:

What Linux? Distribution, version, etc.
Do you play under X or is it without X?
What platform (e.g. "local tiles", "webtiles", or "console")
Do the keys work normally elsewhere?

Remapping the keys via macros seems like an ugly hack to me.

**Comment by fosBHY** [comment]
> What Linux? Distribution, version, etc.
kernel 5.13.13-1-MANJARO
latest manjaro with latest upgrades

> Do you play under X or is it without X?
with X

> What platform (e.g. "local tiles", "webtiles", or "console")
local tiles I would guess ( `make -j4 TILES=y`)

> Do the keys work normally elsewhere (virtual console, xterm)?
yes of course

> Remapping the keys via macros seems like an ugly hack to me.
yes I'd think so too

**Comment by rawlins** [comment]
>  I dont really get where to put this suggested line of code.

On linux I believe the rc file is usually located at `~/.crawlrc`; there's also a separate macro file at this location probably, but the lines I gave are for an rc file. If you hit ctrl-p at the main menu, it should tell you where it read options from. Using the in-game macro menu essentially does the same thing as the rc lines I suggested. For completeness, another rc approach would use the following lower level rebindings, which are maybe a bit more self-explanatory:

```
bindkey += [y] CMD_CAST_SPELL
bindkey += [Y] CMD_FORCE_CAST_SPELL
bindkey += [z] CMD_MOVE_UP_LEFT
bindkey += [Z] CMD_RUN_UP_LEFT
bindkey += [^Z] CMD_ATTACK_UP_LEFT
```

(Note that if you go with this solution, you'll need to clear the macros you've set, which will swap things back! Also, adding options to the rc files does not require you to rebuild crawl and will work with packaged builds as well.)

> Do the keys work normally elsewhere (virtual console, xterm)?

@randomMesh I think you may be misunderstanding the issue. If I'm understanding correctly based on their recent followup, the keys work normally for the poster / as-expected for the locale, but the physical location of the `y` key on this layout means it is not suited to its usual vikeys navigation meaning (`CMD_MOVE_UP_LEFT`) because it can't be used with the right hand. `z` is much more convenient for this meaning. (And then correspondingly, cast mapped to `y`.)

Anyways, I'm going to close this up as I think it is fully resolved.

**Comment by fosBHY** [comment]
yes and thank you all for your help.
