### ISSUE TITLE
Chaos Vault with ghost inside have flammable chaotis trees, instead of wall on border

### ISSUE THREAD

**Issue by Thaneod** [crawl/crawl#2154]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
webtiles 0.28-a0-514-g0d7ab7f379
Serwer: CRAWL.XTAHUA.COM (CXC)
Character : Megustar
_Game still in progress_

**DESCRIPTION:**
New "chaos" Vault which appered in Orc lvl 1 seems to be bugged (or works as designed).
The border of Vault is passable for monsters, and player.  Some walls are replaced with demonic trees, which are flammable, and can be easy destroyed.
This "chaos" Vault still have transporter to go inside, and go outside, and there is ghost of player there.
When I encountered other Vaults with trees, or plants on border before, they was not flammable at all.

![obraz](https://user-images.githubusercontent.com/57416471/134396965-bd49932f-69f1-4da8-8e2b-4073fd0ef450.png)

**EXTRA FILES:**
Game still in progress
[Megustar.txt](https://github.com/crawl/crawl/files/7212846/Megustar.txt)

**Comment by gammafunk** [comment]
This actually is intentional, but it will be changed in a forthcoming commit. Players with a source of fire can burn those trees, releasing monsters to fight them in an easier way. The tree do still block LOS, so unless the player is inside the vault, monsters inside the vault shouldn't be able to burn the trees. 

That said, I'm going to make a commit changing the wall border of these and other ghost vaults that use trees to not have trees in their border. This way we'll be consistent about preventing an accidental player or monster fireball/ligthning bolt/etc from breaking into the vault unintentionally. Right now, at least one vault uses a "destruction veto" to prevent this in a way that's very confusing for players and has other unintentional side effects. And for this vault, there's no good reason to allow bypassing the transporter aspect of the vault for a pretty large set of characters who have fire/lightning bolt attacks. Closing this issue for now, since the current behavior is intentional, but in the near term I'll simply not use demonic trees for the border of this map.
