### ISSUE TITLE
Once I modified the init file, the game starts in full screen

### ISSUE THREAD

**Issue by WallStreetAlpaca** [crawl/crawl#2177]
Once I modified the init file for the first time, simply adding 
explore_delay = 42

the game starts in full screen. Previously it opened in windowed mode.

This is a problem for me because of what may also be a bug, which is when recording in OBS Studio on the full screen DCSS using Game Capture the recording does not update on every single turn while I am playing.\

For example, OBS doesn't record anything from the time that I start the game (intro screen art) until I am in-game and I move a turn. Also while playing, OBS regularly misses turns such as if I swing on a monster. I don't know whether that is a problem with OBS or something in DCSS.

Anyway, the main issue is relevant to DCSS is that full screen being forced after modifying the init. What's the fix?

Thanks.

Win 10, local tiles.

v .271

**Comment by rawlins** [comment]
What happens when you also add `tile_full_screen = false`? Crawl can look for its init file in a few places, and my guess from the description is that there may have been another one somewhere else that is now getting overridden. If you changed the screen resolution, that would have also had this effect (by default, it uses full screen if the resolution is smaller than a specific threshold).

As to the OBS issue, I'm not sure, but there are some streamers on the devteam who may have better responses. You may also want to ask on e.g. the roguelikes discord.

**Comment by rawlins** [comment]
It looks like this more or less got sorted out, so I'm going to close this up. Though, if there is a remaining bad interaction with OBS we would be willing to look into that further, as long as we can replicate them (feel free to open a new issue).
