### ISSUE TITLE
Casting Orb of Destruction at 1% failure rate is dangerous?

### ISSUE THREAD

**Issue by randomMesh** [crawl/crawl#2230]
**PLATFORM and OS or BROWSER:**
Local tiles, Linux

**DCSS VERSION AND GAME INFORMATION:**
Latest master branch.

**DESCRIPTION:**
I've got `Orb of Destruction` (Conjurations) at 1% failure rate but the game nevertheless tells me that it would be "quite dangerous to cast it"?
This is a bug isn't it?

**EXTRA FILES:*
![2021-11-15-220732_1920x1080_scrot](https://user-images.githubusercontent.com/32773707/141854341-e6635c00-32f9-4209-9146-33c5b2ea9175.png)
*

**Comment by lukem12345** [comment]
Looking at spl-cast.cc, The “fail severity adjective” “quite dangerous” is determined by the maximum damage that can be caused by a miscast, not the risk of failure. But the way this sentence is written incorrectly implies that the danger is determined by the risk of failure.

I believe a message like “If this spell fails (1% risk of failure), then it would be quite dangerous.” removes this false implication.

**Comment by lukem12345** [comment]
spl-cast.cc lines 1153-1157
1153 string prompt = make_stringf("The spell is %s to cast "
1154                                      "(%s risk of failure)%s",
1155                                      fail_severity_adjs[severity],
1156                                      failure_rate.c_str(),
1157                                      severity > 1 ? "!" : ".");

Might be better written as something like:
1153 string prompt = make_stringf("If this spell fails (%s risk of failure), "
1154                                      "it would be %s%s",
1156                                      failure_rate.c_str(),
1155                                      fail_severity_adjs[severity],
1157                                      severity > 1 ? "!" : ".");

**Comment by randomMesh** [comment]
Thanks for looking into it!
I would prefer to cast it without confirmation at that failure level, though.

**Comment by lukem12345** [comment]
That’s a great point. You would almost always want to cast a spell if it has a 99% success rate.

Perhaps there should should be an option that allows a player to specify their “minimum miscast risk confirmation”. That could be defaulted to 0% (i.e. always ask for confirmation if there is any risk of failure, which is the current behavior), but if you want you could specify that unless the risk of failure is greater than e.g. 1,2,3,4,5…%, you would always want to cast.
I think a feature request for an option like that would be appealing to the majority of players.

**Comment by rawlins** [comment]
This is not a bug, exactly because miscast damage and fail rate are not fully correlated, especially for high level spells. I don't think that it would be great to add a % option exactly because of cases like this: red miscast damage can potentially one-shot a player at half health. You can always set the miscast level to `4` and it will not trigger on a red miscast.

**Comment by randomMesh** [comment]
It may not be a bug but like @lukem12345 said the wording could be changed to remove the false implication that the danger is determined by the risk of failure.

**Comment by ebering** [comment]
Went with a different clarifying warning: "This spell is %s to miscast (%s risk of failure)%s Continue anyway?" to clarify that you're being prompted about a bad thing that could happen, and the chance of that bad thing.

**Comment by randomMesh** [comment]
These 3 additional letters make quite a difference. Thanks!
