### ISSUE TITLE
Nu trap flavor messaging in zot is odd

### ISSUE THREAD

**Issue by ardl** [crawl/crawl#2270]
**PLATFORM and OS or BROWSER:**
current trunk cbr2

![image](https://user-images.githubusercontent.com/70080435/144725715-4955d926-a2da-44f2-8543-1c84836f5dda.png)

**Comment by Goratrix** [comment]
I haven't tested it, but it looks like it also gives bad messaging in a few other branches, because it uses shortname:
`mprf("A sudden malevolence fills the %s...", branches[you.where_are_you].shortname);`
So you would get 'the Dis' and similar. Looking at branch-data.h, it feels like removing 'the' and using longname would generally look better here... although some (Pandemonium, Hells except Dis) don't have an article, so maybe they would look strange.
