### ISSUE TITLE
Spells sometimes not appearing in spell library in console after searching for them

### ISSUE THREAD

**Issue by NinthSettler** [crawl/crawl#2303]
**PLATFORM and OS or BROWSER:**
Console, Windows 10. Putty.

**DCSS VERSION AND GAME INFORMATION:**
0.28-a0-1213-g0243856f03 Trunk

**DESCRIPTION:**
Searching for a spell in the M menu using Ctrl-F sometimes gives you the spell in webtiles spectator but it doesn't in console. 

**EXTRA FILES:**
Twitch clip: https://clips.twitch.tv/EnjoyableSparklyFalconWoofer-i-mPP43vzZPx9K62

You can clearly see that Dispel Undead appears in the webtiles spectator side but it does not appear on console (lower right corner)

http://crawl.kelbi.org/saves/NinthSettler-crawl-git-0243856f03-211221-0701.tar.bz2

**Comment by rawlins** [comment]
It's been a while, but can you clarify what the save is relative to this bug report? In that save, dispel undead is already memorized (in slot `u`). (When I amnesia the spell on this save I can't recreate the console bug, but a lot of stuff would be reset by amnesia.)

**Comment by NinthSettler** [comment]
I'm sorry, the save was created after I memorized the spell. You might find
the same issue doing ctrl f for different spells. The save might be of help
since I have a fair amount of spells already. I don't know how to
consistently replicate it but it has happened multiple times, seemingly at
random.

Sometimes I search for spells in my library with the Ctrl f function and
they don't appear on console but they do in tiles.

**Comment by rawlins** [comment]
Aha, I figured this out, the clue was actually in your twitch clip: if you are sufficiently scrolled down, the menu doesn't correctly reset the scroll on search, and so the menu item is invisible above the top of the screen locally (a fix shouldn't take me too long but you can just scroll up if you hit this again). In current trunk this can now only be fully replicated with `menu_arrow_control=false`, because the hover ensures that something is visible.

**Comment by NinthSettler** [comment]
I'm glad the clip helped. Not the way I was thinking of helping DCSS when I
started streaming, but we take it.
