### ISSUE TITLE
Phial not working correctly on Convoker

### ISSUE THREAD

**Issue by Shapermc** [crawl/crawl#2331]
Webtiles, CKO, Chrome,  Dungeon Crawl Stone Soup version 0.28-a0-1389-gc726bef33b (webtiles), TeSu^Sif

Somewhere just before turn 77658 I used Phial of Floods on a convoker who was reciting recall. The order of operation in the messages shows that I hit him with the blast of water, then the recall still went off afterwards, and he was not given the waterlogged status. Unsure how to give more information. I have screen capped and relayed the combat log from the point of recall being used through my next action after the recall went off: 

![image](https://user-images.githubusercontent.com/80350699/147890346-dd8a8d9f-7d63-4f87-affd-ed5142a08c02.png)

Please let me know if I can help in any other way.
[ShapermcTeSu.txt](https://github.com/crawl/crawl/files/7799837/ShapermcTeSu.txt)

**Comment by perryprog** [comment]
I tried a bit to reproduce this and it seems the most likely way this can happen is if the location the convoker is knocked back onto is a non-floor/water feature, like a staircase. This prevents the shallow water from being generated in `create_feat_splash`, which leads to no water logging.

It looks like the center tile of the "pool" is being forced to generate, and that center is always the location of where the creature gets knocked back, so I doubt that could be the cause here.

**Comment by perryprog** [comment]
Note that pull request _probably_ closes this ticket, assuming my guess at what happened is correct. :)
