### ISSUE TITLE
As an Ashenzari worshiper I don't have full piety with whole eq cursed

### ISSUE THREAD

**Issue by Nattfarinn** [crawl/crawl#2358]
**PLATFORM and OS or BROWSER:** webtiles [macOS Safari, Version 14.1.2 (16611.3.10.1.3)]

**DCSS VERSION AND GAME INFORMATION:** 0.28-a0-1506-g3893175d92

**DESCRIPTION:** As an Ashenzari worshiper I have my whole eq cursed, but I don't have full piety and Ashenzari still offers me curses. May be relevant, that `macabre necklace` has been generated during this game (but I haven't wear even for a turn).

**EXTRA FILES:**

<img width="504" alt="Screenshot 2022-01-14 at 16 36 58" src="https://user-images.githubusercontent.com/5822569/149546170-d33245ea-f275-471f-ae4f-08c8bc5df693.png">

Save: https://underhound.eu/crawl/saves/Nattfarinn-crawl-git-3893175d92-220114-1600.tar.bz2

#### Reloading the game solved the issue

**Comment by semitonal** [comment]
I don't have save file access so can't check, but did you curse any of your items while in the Abyss by any chance? If so that would explain this behaviour (currently Ashenzari won't properly grant piety for curses made in the Abyss, but they'll update properly again when it next recalculates after leaving). If so then I'm working on a fix for that shortly, if not then maybe there's some other issue as well.

**Comment by ebering** [comment]
I checked the save, this appears to be fixed by @semitonal 's general abyss piety fix.
