### ISSUE TITLE
Need to remove a name from the pool of randarts - the amulet "Cunt"

### ISSUE THREAD

**Issue by murtidash** [crawl/crawl#2362]
![image](https://user-images.githubusercontent.com/6403900/149638161-74dacc98-1f74-4150-9464-3a9fe7f071e4.png)

This was generated via a gozag jewelry shop.

https://cbro.berotato.org/morgue/murtidash/murtidash.txt

**Comment by ebering** [comment]
This was randomly generated by the random name generator, it's not from the preprogrammed list. These sorts of outputs from the name generator are pretty hard to avoid, because even with a "bad words" list the random name generator loves to produce things that phonetically sound dirty to a human, like the classic "2 scrolls labeled FUK DA SAC".

**Comment by murtidash** [comment]
Fair enough, I would think that it's easy enough to add multiword strings to a deny list to match against but then again since this is all volunteer stuff I get the lack of desire to implement it. :)
