### ISSUE TITLE
Lindwurm casts spell while frightened in CAO webtiles trunk

### ISSUE THREAD

**Issue by erichfiederer** [crawl/crawl#2378]
**PLATFORM and OS or BROWSER:**
 Webtiles, chrome 97

**DCSS VERSION AND GAME INFORMATION:**
Morgue file: http://crawl.akrasiac.org/rawdata/Boodz/morgue-Boodz-20220123-190631.txt

**DESCRIPTION:**
I used a fear scroll which successfully feared a lindwurm, but while running away the lindwurm was able to cast a spell.

**EXTRA FILES:**

**Comment by erichfiederer** [comment]
![image](https://user-images.githubusercontent.com/98294694/151090790-6e464566-2f88-4d17-b277-e2d0b79a8bcb.png)

Attached is an image during the bug

**Comment by rawlins** [comment]
I tried to replicate this a few times and couldn't figure out how to get it to happen. It's conceivable it's some interaction with the Torpor snail + energy timing. I guess it's also conceivable that it could be something like, the fear wore off immediately and there was a message timing bug? (Where the messaging about it ending didn't come because of the death.) But I'm not sure how technically feasible either of these is, and the lindwurm still shows as `fleeing` in the log.

**Comment by erichfiederer** [comment]
Thanks for looking rawlins! I'll let you know if I run into it again.

**Comment by PleasingFungus** [comment]
Fixed in 7b59d4eb9773022964edb2804ddae7787e4cf114. Sorry for the delay, and thanks for reporting!
