### ISSUE TITLE
Game crashes upon moving cursor over staff on ground

### ISSUE THREAD

**Issue by Jellyblob** [crawl/crawl#2397]
**PLATFORM and OS or BROWSER:**
Local Tiles, Windows 10 Build 19042.1466 (build may be inaccurate as I believe my computer updated overnight. If there is a way to recover the data of which build I was running at the time of the crash, please let me know and I will get it for you) 

**DCSS VERSION AND GAME INFORMATION:**
Version: 0.27.1 
Seed: 12700919657783936407 
Dungeon:10

**DESCRIPTION:**
I was hovering my cursor over a staff on the floor to view the name and my game would crash every time my cursor would move over the staff. Nothing was happening at the time and I was able to reproduce the crash 8 times before I stopped. There was no specific sequence that caused this issue, I tried replaying the floor and going back to the staff after the initial crash multiple times, going up a level before going back down to attempt to hover over the staff, saving and exiting my game on a different tile than the auto-save and reloading the game, and different window sizes and placements all to no avail. Here is gif I took of the issue: 
![sCxsqiB](https://user-images.githubusercontent.com/44444294/152172261-b51ddc03-876e-48e3-9d55-b340bb9de61e.gif)

**EXTRA FILES:**
Here are all of the logs from that character: 
[Files for Report.zip](https://github.com/crawl/crawl/files/7987262/Files.for.Report.zip)

**Comment by rawlins** [comment]
Thanks, this is long-fixed in trunk as well as in the 0.27 stable branch in online play (1e3a1f79142), unfortunately we never managed to do another 0.27 release that includes the fix (we may do a final 0.27 bugfix release around when 0.28 is released, later this week). As a workaround, the crash is only if the staff is unid'd, so if you move over any staffs you see, that should head it off.
