### ISSUE TITLE
No error message / silent failure when trying to load a save open in another binary

### ISSUE THREAD

**Issue by miguno** [crawl/crawl#2501]
**PLATFORM and OS or BROWSER:**
macOS 12.3 Monterey, M1 MBP. Running DCSS v0.28.0 with local tiles.

**DCSS VERSION AND GAME INFORMATION:**
Release v0.28.0, the latest version as of today.

**DESCRIPTION:**
I can launch the tiles-version of DCSS and can see the menu screen. But only some buttons are functional, whereas any "play" related buttons don't do anything.

- Buttons that do work include "Instructions", "High Score".
- Buttons that don't work include "Dungeon Crawl", "Tutorial for Dungeon Crawl". I can click on these latter buttons, but nothing happens.

I don't see any error message, even when I manually launch the .app from a terminal.

FWIW the console version works just fine on the same Mac.

**EXTRA FILES:**
I'd be happy to include any log files but don't know where to find them. The game has not presented any error messages to me.

**Comment by miguno** [comment]
After a few hours I tried again (without rebooting the laptop or any other changes), and now it works. Can't reproduce it thus far. 🤷

**Comment by hexwab** [comment]
Can reproduce on Crawl 0.28.0 (ubuntu package, x86-64), also observed on 0.26.
I cannot started a new game from the main menu, including tutorial modes, with my usual character name of "HEx". No errors, just nothing happens. Other menu options (Arena, Instructions, Sprint, High Scores) work fine. After changing character name it works fine. 
After removing `~/.crawl/saves/HEx.cs` everything works again (and conversely). Maybe this file was corrupted somehow?
[HEx.cs.gz](https://github.com/crawl/crawl/files/8591955/HEx.cs.gz) (gzipped because github seems picky about file extensions)

**Comment by rawlins** [comment]
@hexwab to clarify, you are unable to load that save? The main menu buttons shouldn't let you start a new game with the same name as an existing save, but should load that save instead. I couldn't replicate this on mac tiles/trunk with that save; expected behavior that I'm seeing: when I type the name it selects the save in the save browser, and when I have typed in that name and mouse over the new game buttons etc it clears the name.

I'm not sure yet if this is the same bug but I'm going to at least temporarily reopen so that it is harder to miss.

**Comment by hexwab** [comment]
So this is puzzling. Revisiting this a few days later, I loaded the file with no problem, which turned out to be a perfectly ordinary DECj on D:1.

To be super-specific, here's what I did today:
(1) Placed the HEx.cs file in ~/crawl/saves/, where I had removed it from.
(2) Started crawl at a terminal.
(3) Got a main menu with a "Saved games" section containing an item for "HEx, a level 1 Deep Elf Conjurer".
(4) Selected that item and the game started, showing a starting character. (Would I have saved a character on turn 1? Not sure why I would but I don't remember. Yes, I had been playing DECj.)  Selecting "New game" instead also worked.

None of this is what happened a few days ago:
(1) Started crawl at a terminal.
(2) Got a main menu with no "Saved games" section.
(3) Selected "Dungeon Crawl" from the "Choices" section.
(4) No response whatsoever. It's as though I hadn't pressed enter at all.
(5) Tried Dungeon Sprint, which worked. (After a game of Sprint, selecting "Dungeon Crawl" from the menu immediately jumped the selected item down to "Dungeon Sprint", as though I'd instead pressed the down arrow four times.)
(6) Quit crawl and removed the aforementioned HEx.cs from ~/.crawl/saves/.
(7) Started crawl at a terminal. Game works normally.
(8) Quit crawl and copied HEx.cs back to ~/.crawl/saves/. Game refuses to start again.
(9) Removed clearly broken savefile and commented on github.

This identical behaviour has occurred to me *once* before, on ubuntu's 0.26 package, and IIRC I solved it the same way (by removing a .cs file from ~/.crawl/saves).

**Comment by rawlins** [comment]
Ah, thanks for the detail; I think I actually do know what would is likely to be the cause of both reports. If you are playing a game in another process with the same username, crawl won't show the save in the browser and won't let you start a game with the same username as the ongoing game. Removing the save manually will let a game start with that username in the second process (though one or the other is likely to get overwritten sooner or later). So I think this is a bug but more or less a UI bug -- it should give a more informative error for that case.

**Comment by hexwab** [comment]
My, I do feel silly. Turns out I do (still!) have an active crawl process (with a DECj on D:1) stashed away. I do feel slightly better that at least one other person can't keep track of all the stuff they have open :)

But yes, the game's response to this is super head-scratching.

**Comment by miguno** [comment]
Closing for now. Feel free to reopen if needed.
