### ISSUE TITLE
Compiling on macOS: build finishes with success, but launching crawl fails with "The file /Resources/crawl does not exist."

### ISSUE THREAD

**Issue by miguno** [crawl/crawl#2502]
Hi there, I am trying to familiarize myself with the code base and was attempting to build crawl locally on my Mac laptop.

# Environment

* macOS 12.3 Monterey (M1 MBP 2021)
* crawl as of 4c793a2ed2, i.e., latest `master` as of today
* Built according to https://github.com/crawl/crawl/blob/master/crawl-ref/INSTALL.md#macOS

# Problem 1: `crawl` binary fails to launch

The build runs successfully, but launching the compiled `crawl` binary fails with:

```sh
# ...previous steps omitted for brevity...
$ cd crawl-ref/source/

# Build console version;
# Note: The tiles version, built with `make TILES=y` or
# `make -j4 mac-app-tiles TILES=y), fails too
$ make -j4
...
    CXX rltiles/tiledef-unrand.o
    CXX main.o
    CXX util/levcomp.tab.o
    CXX util/levcomp.lex.o
    GEN compflag.h
    CXX version.o
    LINK crawl
$

$ mac/crawl
The file /Resources/crawl does not exist.
```

**What I expected:**

* The `crawl` binary should have be located at `crawl-ref/source/crawl` (there was no file at that location) as documented at https://github.com/crawl/crawl/blob/master/crawl-ref/INSTALL.md#compiling, but it actually is located at `crawl-ref/source/mac/crawl`.
* The `crawl` binary launches successfully.

# Problem 2: Build creates a broken macOS app (zip)

A second error, likely related, is that the `crawl` binary is missing from the macOS app ZIP file when adding `mac-app-tiles` to the `make` command. Here's an excerpt of my ZIP file contents (see https://pastebin.com/XyXs4K4q for full list):

```
Dungeon Crawl Stone Soup - Tiles.app/
└── Contents/
    ├── Info.plist
    ├── MacOS/
    │   ├── Dungeon Crawl Stone Soup - Tiles*
    │   └── contrib/
    │       └── fonts/
    │           ├── DejaVuSans.ttf
    │           └── DejaVuSansMono.ttf
    └── Resources/
        ├── CREDITS.txt
        ├── Crawl.icns
        ├── LICENSE.txt
        ├── dat/
        │   ├── ...removed for brevity...
        ├── docs/
        │   ├── ...removed for brevity...
        ├── settings/
        │   ├── ...removed for brevity...
[...]
```

**What I expected:**

* The app/the ZIP file includes the `crawl` binary.
* The app can be launched.

**Comment by rawlins** [comment]
Sorry for the slow reply, I think all the mac based devs have been away from the project lately.

First, the file in `mac/crawl` is unrelated to the build process, it's a (non-generated) script that is part of the repository (you can see it here: https://github.com/crawl/crawl/blob/master/crawl-ref/source/mac/crawl) and is used in constructing the mac console app build. It's not expected to work with no arguments at the command line.

Second, I can't replicate the rest of 1 -- the build process is supposed to create a binary named `crawl` in the `source` directory following the build command you showed and it does on all my devices. (Additionally we do test mac builds in CI and it hasn't broken.) Can you verify that you've tried to run the right thing, e.g. `./crawl`? It wasn't in the pasted output at least.

On the contents of the zip file: what you are seeing is the expected outcome for the tiles app. The binary `crawl` is renamed to `Contents/MacOS/Dungeon Crawl Stone Soup - Tiles`. Things are a little different on the console app, because the main executable in `Contents/MacOS` is the above-mentioned scripts that then runs the crawl binary (which shows up unrenamed in `Resources`) in terminal. Does that clarify things?

**Comment by miguno** [comment]
Thanks for the response!

I updated my local repo to the latest upstream today, and the `source/crawl` binary is now being generated. Didn't change a thing on my side, so all I can say is ¯\_(ツ)_/¯ and close this issue. :)

**Comment by Napoleon-BlownApart** [comment]
I'm having trouble building the latest master on MacOS as well:
```
 make -j4 mac-app-tiles TILES=y
Configured with: --prefix=/Applications/Xcode-12_4.app/Contents/Developer/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/c++/4.2.1
/Applications/Xcode-12_4.app/Contents/Developer/usr/bin/make -C rltiles all ARCH=x86_64-apple-darwin19.6.0 NO_PKGCONFIG=Yes TILES=y
  * If you experience any problems building Crawl, please take a second look
  * at INSTALL.md: the solution to your problem just might be in there!
    PYTHON species-data.h
    GEN ../docs/crawl_manual.txt
    COPY ../docs/quickstart.txt
Traceback (most recent call last):
  File "/Volumes/VM_TM/Games/DCSS/crawl/crawl-ref/source/util/species-gen.py", line 23, in <module>
    import yaml  # pip install pyyaml
ModuleNotFoundError: No module named 'yaml'
make: *** [species-data.h] Error 1
make: *** Waiting for unfinished jobs..
```

I have installed pyyaml and have v6.0:
```
pip install pyyaml
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: pyyaml in /usr/local/lib/python3.9/site-packages (6.0)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
```

I'm also getting `libpng` warnings:
```
libpng warning: Interlace handling should be turned on when using png_read_image
```

I'm not sure what to do now.

**Comment by rawlins** [comment]
Most likely you have multiple python versions, and default path `pip` is associated with a different version than what the build process is calling. I would check things like `which python` / `which python3` / `python --version` / `python3 --version`. The build process will prefer a binary named `python3` if one exists. This can happen with system python vs homebrew, and if you have e.g. an anaconda install that will complicate things further.

`libpng` warnings can be ignored.

Also, best to open a new issue rather than reply to an old, closed issue -- it's only happenstance that I actually saw this (and the original issue is unrelated to this question).

**Comment by Napoleon-BlownApart** [comment]
Thanks!!  Python versions was the problem.  Mine was pointing to 2.7, so I changed it to 3.10 and viola, it works and runs perfectly.
