### ISSUE TITLE
Vampire Poison after Bloodless

### ISSUE THREAD

**Issue by tr2424** [crawl/crawl#2550]
This is likely working as intended, but just in case. Noticed that if my Vampire is poisoned while "Alive," and I switch to "Bloodless" the poison icon stays on the character but does no damage. Am guessing that's because as undead, it is immune.

**Comment by semitonal** [comment]
This is intended behaviour, yeah - gaining poison immunity by becoming fully undead (or nonliving, through statue form) doesn't cure any existing poison, but just pauses it. I could see an argument either way for changing that (since gaining poison immunity through Zin or the staff of Olgreb does let the poison continue to tick down), but I think it's also probably fine as-is.
