### ISSUE TITLE
Period key is a footgun for conjurers

### ISSUE THREAD

**Issue by natelastname** [crawl/crawl#2593]
**PLATFORM and OS or BROWSER:**
Local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.28

**DESCRIPTION:**
The period key should not cause the player to wait one turn because this key is also used to continue casting spells such as Searing Ray. It is far too easy to press the period key one extra time during a battle, and there are other already other buttons that can be used to wait one turn (e.g., numpad 5).  

**EXTRA FILES:**
N/A

**Comment by gdbing** [comment]
I don't think this warrants a default key remap, but the issue could be addressed with an option to throw up a warning/confirmation when player tries to rest after they finish channelling Searing Ray or Flame Wave

**Comment by floyza** [comment]
Note that if you are using vim-keys instead of a numpad, the period key is what you use for waiting a turn.

**Comment by rawlins** [comment]
For better or worse, the gimmick of these spells is that they continue casting on wait; here's the in-game description of searing ray:

```So long as the caster maintains focus upon the spell and supplies it with magical
power (by waiting in place and not taking any other actions), the ray will
follow the caster's target if it should move.```

Per the request in the original question, we are unlikely to change `.` to a default binding other than `CMD_WAIT`, this is a long-standing dcss (and roguelike) binding. (Also, if there's a key bound to `CMD_WAIT` that doesn't continue searing ray, that is actually a bug.) My main recommendation is to quiver these spells and fire with `p` or shift-tab, which will auto-continue or recast instead of waiting. Or play slower :-).

I'm going to close this issue, though that doesn't preclude someone implementing the warning idea (though it feels more like custom rc lua territory to me). It's possible the gimmick itself should change.
