### ISSUE TITLE
MP drained by swapping melee/ranged weapons if one has MP+

### ISSUE THREAD

**Issue by powerbf** [crawl/crawl#2622]
webtiles trunk

A recent change made it so that your current MP is reduced when swapping out an item with an MP+ property on it.
The intention seems to be to stop casters swapping out an MP+ item after using up the extra MP.

> 94e2008b86 | Nicholas Feinberg | 2022-05-07 09:20:37 -0700
> 
> Remove MP when un-equipping +MP items (ɯ|s|ı|ʍ|o|ǝ|ɯ)
> Encourage making choices ("do I want +MP or wizardry?),
> rather than swapping off your =mp halfway through every
> fight.

However, this also means if you have MP+ on your melee or ranged weapon, your MP can get drained all the way to zero just by swapping 2 or 3 times (which you may want to do in some situations, for example, an enemy that blinks in and out of melee range, or enemies that are coming in "waves"). This can make a weapon with MP+ on it useless, even for a character that doesn't really benefit from the extra MP, but just wants the normal amount for using god abilities, evocable blink, etc. It also penalises swapping items for specific resists. This would seem to be an unintended consequence of the change.

Proposals:
a) revert the change (simple)
b) preserve the ratio of current MP to max MP when swapping. For example, if MP is 20/29 with an MP+9 item equipped, change to 14/20 when unequipped. If the item is equipped again then MP goes back to 20/29 for no net change. This still penalises a caster swapping out an MP ring (they lose 6 MP in this example) while keeping weapon swapping feasible.

**Comment by PleasingFungus** [comment]
Thanks for bringing this up!

The issue you bring up seems quite niche, since there are few weapons that have +MP on them, and I'm not convinced that it's actually a problem. The current situation is simple to describe and to understand - it does make weapon swapping much weaker in these cases, but I'm not convinced that's a bad thing. Reverting the linked change or adding a more complex, harder to describe & understand mechanic seems counterproductive.

Please let me know if I'm overlooking something!

Cheers,
PF
