### ISSUE TITLE
Local Tiles: Screen doesn't redraw when using number pad to move.

### ISSUE THREAD

**Issue by Rydian** [crawl/crawl#2644]
**PLATFORM and OS or BROWSER:**
Local tiles, Windows 10.

**DCSS VERSION AND GAME INFORMATION:**
0.29-a0-993-g4a18f31a58 (tiles)

**DESCRIPTION:**

- When using the number pad to move, nothing appears to happen.  I can move multiple spaces while it's not redrawing.  If I hit escape afterwards, then the screen updates to show the changes.
- Using 7/u and such to move doesn't have this issue.
- Using the arrow keys to move doesn't have this issue.

Happens on all characters old and new.
Happens with the default init, a custom init, and no init file.

**EXTRA FILES:**

**Comment by Goratrix** [comment]
I just tested it with latest trunk (0.29-a0-998-g1987434951) and yes it does happen, but important clarification: it happens only when numlock is ON, i.e. when the numpad is supposed to capture/send numbers. But instead of sending numbers, it seems to capture the directional input, but captures it into some buffer without refreshing the screen (screen only refreshed all at once after a different key is pressed).

When numlock is OFF, the numpad works correctly for directional input.

However, at the same time when numlock is OFF, numpad keys are actually captured as numbers in text inputs (for example ctrl+f), but they are not captured as numbers when they actually should be (with numlock ON), so this is getting really confusing...
