### ISSUE TITLE
Skill Targetting Does Not like the Number 3

### ISSUE THREAD

**Issue by rredelmeier** [crawl/crawl#2697]
**PLATFORM and OS or BROWSER:**
Webtiles, CBR2, Firefox

**DCSS VERSION AND GAME INFORMATION:**
Morgue at https://cbro.berotato.org/morgue/ragingrage/ragingrage.txt
Same morgue can be found at https://pastebin.com/8MehDurr if there are any issues

**DESCRIPTION:**
Trying to set skill targets at a number ending in 3, instead sets them to that numbers first digit. I.e. 13 becomes 1 (how I initially discovered it, see the attached GIF), 3 does nothing (leaving it unset, or leaving it at whatever it had been set at), and 23 sets the skill target to 2). Other than this, the skill target feature behaves normally. 

**EXTRA FILES:**

[Unlucky Skill Target 13](https://user-images.githubusercontent.com/16259668/187768603-1ec97868-adcf-44cb-90d5-d882e7ca3990.gif)

**Comment by rawlins** [comment]
Thanks for the report! What's happening here is that you [have a keymap](https://cbro.berotato.org/rcfiles/crawl-0.29/ragingrage.macro) that maps `3` to `af`. It's sort of a longstanding issue that the keymap context for the skill menu uses the regular context, but, this keymap does apply in this context, preventing you from entering the number 3. I would recommend trying to find a way to do whatever this is with macros (instead of keymaps, e.g. macroing `zaf` instead), or with a key other than a number key.
