### ISSUE TITLE
Arcjolt crashes the game with Uskayaw, presumably due to pain bond

### ISSUE THREAD

**Issue by Flugkiller** [crawl/crawl#2726]
**PLATFORM and OS or BROWSER:**
Webtiles, Google Chrome

**DCSS VERSION AND GAME INFORMATION:**
0.29.1-debian-1-gc3f1650bb9

**DESCRIPTION:**
Playing with Uskayaw, the game crashes sometimes when using Arcjolt. Pretty sure it's yet another pain bond crash.
Pretty easy to replicate.

**EXTRA FILES:**
https://crawl.xtahua.com/crawl/morgue/Flugkiller/crash-Flugkiller-20220913-040823.txt
https://crawl.kelbi.org/crawl/morgue/Flugkiller/crash-Flugkiller-20220912-072537.txt
https://crawl.xtahua.com/crawl/morgue/Flugkiller/crash-Flugkiller-20220913-040741.txt

**Comment by Rydian** [comment]
I'm also crashing with Arcjolt, but I believe this is due to summoner mechanics.  If the jolt kills a summoner (thus poofing the summon) and then tries to arc to a summon that just poofed, it's a crash.

I've recreated it in Wizard mode by finding an open area, spawning a bunch of Boggarts, yelling at them so they summon, then casting Arcjolt when there's a bunch of summons that are further away than the Boggart (and thus will be arced to afterwards).

PLATFORM and OS or BROWSER:
Local tiles, Windows 10

DCSS VERSION AND GAME INFORMATION:
0.29-a0-1180-gc3f1650bb9

EXTRA FILES:
This is a save that will always crash if you load it up and hit z and then b (to cast Arcjolt).
Also has logs and junk.
[Crashjolt.zip](https://github.com/crawl/crawl/files/9555443/Crashjolt.zip)

**Comment by Flugkiller** [comment]
Aha, what you're describing seems reasonable as that would happen with pain bond too regardless of summons (arcjolt kills a monster during pain bond, the next target that it tries to arc to just died due to pain bond and it crashes)

**Comment by Rydian** [comment]
https://github.com/crawl/crawl/commit/b27577e5d98d6b841546ce5ce30f1ada2abb5d54
That commit fixed the issue in the save at least.

**Comment by semitonal** [comment]
Should have been fixed by that commit linked by Rydian, thanks for reporting!
