### ISSUE TITLE
spider form attacking with "front legs"

### ISSUE THREAD

**Issue by T-Minutiae** [crawl/crawl#2742]
Version: Windows local tiles 0.30-a0-134-gb40fab5c76

When in spider form and examining a monster with x-v, the game will claim that the monster has a X% to evade your front legs. This is consistent with other forms but it is rather akward in the case of spider form. It is also inconsistent with what the A, % and possibly other screens and messages tell the player. "Fangs" or something among those lines would make more sense.

![spider form front legs](https://user-images.githubusercontent.com/114019424/191352750-d9001532-8d38-4ffc-91b3-5a6c7c779827.png)

**Comment by SamanthaTobias** [comment]
"front leg" is the spider form "hand name" value. changing this to something that is clearly not analogous to a hand might lead to some other similarly inappropriate scenarios. although due to not being able to wield anything anyway most of those should not be possible in the first place.

a related issue which is definitely wrong: in the 'A' menu your fangs are described as poisonous rather than venomous. 
![image](https://user-images.githubusercontent.com/114337819/192147588-2d38e3bc-55d3-44f7-928c-07a02db27d70.png)

**Comment by kd7uiy** [comment]
We could change the name to Front Pincers, which should still  be "hands" but doesn't imply legs. 

Also agree with the poisonous fangs, but poison and venom are used pretty interchangeably in game, and I think it would be confusing to change the name to venom, as poison is what is usually used in game...

**Comment by Picklenugget1** [comment]
"You are a venomous arachnid creature"
"You have poisonous fangs"
Probably should use the same for both of these. Probably venom, as that is used in the brand (ie. +0 dagger of venom)
