### ISSUE TITLE
Cheibriados Temporal Distortion and Eringya's Noxious Bog

### ISSUE THREAD

**Issue by Sazzach** [crawl/crawl#2749]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.29.1

**DESCRIPTION:**
Using Temporal Distortion makes Eringya's Noxious Bog expire, but does not make the bog status expire. Normally when the spell expires, the bog status does as well.

To reproduce: cast Eringya's Noxious Bog and then use Temporal Distortion.

**EXTRA FILES:**

**Comment by Monkooky** [comment]
Also works with step from time.

**Comment by kd7uiy** [comment]
Looking at all of the duration effects, I believe this should also be done for DUR_LIQUEFYING, DUR_SENTINEL_MARK, and DUR_MESMERISED, in addition to the one for bog, DUR_NOXIOUS_BOG.

Being marked seems like something of an alarm going off in the dungeon, so it should go off with time. Liquefying is the same issue. Mesmerised is really a result of the monster affecting you, so that should be limited I would think. 

I can see a few potential solutions to this, most likely editing the _run_time_step() function in god-abil.cc, or possibly playing around in timed-effects.cc. Will ponder this some more.
