### ISSUE TITLE
Missing line about flight for black draconian knights

### ISSUE THREAD

**Issue by Solitudinal** [crawl/crawl#2752]
**PLATFORM and OS or BROWSER:**
webtiles on chrome

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-165-g1891117ce2

**DESCRIPTION:**
Black draconians and black draconian knights can fly, but only plain black draconians state this in their x v description.

**EXTRA FILES:**
![knightflight](https://user-images.githubusercontent.com/100310764/192753742-6a9a14f7-f2a2-42da-aeab-3d9c85669039.jpg)

**Comment by kd7uiy** [comment]
Trying to root out the cause of this, taking a few notes so that someone who knows more can hopefully know where to look.

1. Some, but not all, Draconians can fly. Some also have other special abilities.
2. mon-data.h has the special abilities by draconian type. 
3. mon_special_ability.cc has the ability to overwrite abilities. I believe that a section for Draconians should be added, which basically ors the type or subspecies abilities. This likely is the fix. This is similar to what is done with resistances

If no one else has fixed it I'll try this out sometime in the next 2 days to see what it does. Looking at the mon-data.h file I believe this will only affect black draconians that aren't the default class, like knights and such.
