### ISSUE TITLE
Stealth bugged in statue form, more stealthy rather than less.

### ISSUE THREAD

**Issue by b2** [crawl/crawl#2803]
**PLATFORM and OS or BROWSER:**
webtiles - Firefox 106.0.2

**DCSS VERSION AND GAME INFORMATION:**

Game seed: 1 (custom seed) (seed may be affected by game upgrades)
Version history for your current game:
Game started: 0.30-a0-324-g6d2431741b
0.30-a0-329-g85436e0
0.30-a0-339-g89bb51ec76
0.30-a0-341-g6827065

**DESCRIPTION:**

Assuming statue form increases stealth dramatically but says "You feel less stealthy" 

<img width="853" alt="Screen Shot 2022-11-01 at 11 13 45 AM" src="https://user-images.githubusercontent.com/180862/199295272-f0d0f731-d3a2-4dea-8cbd-1fbce3929643.png">
Go to Statue Form:
<img width="620" alt="Screen Shot 2022-11-01 at 11 17 50 AM" src="https://user-images.githubusercontent.com/180862/199295826-07606356-b96f-4bb3-bae6-6727e69799bf.png">

However, note the increase in stealth. Also, rPois is now infinite of course, because of statue, so that message was in error also. 
<img width="853" alt="Screen Shot 2022-11-01 at 11 13 09 AM" src="https://user-images.githubusercontent.com/180862/199295278-9055d876-7541-415e-abb9-cbe8a36ccfc0.png">
Ending transformation:
<img width="631" alt="Screen Shot 2022-11-01 at 11 19 41 AM" src="https://user-images.githubusercontent.com/180862/199296193-dae6a0d0-6ff0-4575-b70b-2fe7c3a4a250.png">

**Comment by kd7uiy** [comment]
You were less stealthy because of the loss of your boots of stealth. You gained stealth because your chain mail was melded, essentially rendering it not an issue. Overall it was a net increase of stealth.

**Comment by b2** [comment]
> You were less stealthy because of the loss of your boots of stealth. You gained stealth because your chain mail was melded, essentially rendering it not an issue. Overall it was a net increase of stealth.

Yes, I thought that was why my stealth changed in unexpected directions.  The message was wrong here both coming and going from statue form, probably because it doesn't actually check current conditions to generate it, since statue reduces stealth by itself.  A minor issue, at best.

**Comment by Picklenugget1** [comment]
Wait, can someone check that statue form reduces stealth? I don't think it does, but i could be wrong. The "less stealthy" message I know is from the melded boots though.

**Comment by kd7uiy** [comment]
@Picklenugget1 The less stealthy is because the boots increase stealth, thus them melding decreases stealth. The increased stealth was a result of the chain mail being melded. As chain mail isn't very stealthy, there was a net increase in stealth, when all was taken in to account.

So far as I can tell, Statue Form doesn't actually directly affect stealth one way or another. In fact, so far as I can tell, no transformation can affect stealth in any way other than melding of gear as seen above. But I could be missing something...

**Comment by Picklenugget1** [comment]
So, in order to fix the incorrect status messages we would need to make them reflect what actually happens, am I correct?

**Comment by kd7uiy** [comment]
It's something that almost certainly happens with all transformations that involve melding. What would have to be done is to check for the actual result instead of just looking for modifiers as seems to be the case now. I know stealth would be affected, I'm not sure what would happen if we had resistances with both ways happening, it's likely not limited to just stealth.

**Comment by PleasingFungus** [comment]
I understand why you were confused, but trying to fix this seems like an endless rabbit hole. Should we change the rPois message that pops up ("you no longer feel resistant to poison")? What about +str items melding when you cast eg Dragon Form?

The messages that are printed are solely and exactly the equip/unequip messages for your melded/unmelded equipment. I don't think it's particularly useful to try to print all changes of stats that occur when you transform, so let's not.
