### ISSUE TITLE
"Ran out of altars for temple!" x3

### ISSUE THREAD

**Issue by thirdmesn** [crawl/crawl#2810]
**PLATFORM and OS or BROWSER:**
local tiles

**DCSS VERSION AND GAME INFORMATION:**
0.29.0
game seed: 15011161759471765859

**DESCRIPTION:**
"Ran out of altars for temple!" at game start. I died before actually reaching the temple.

**EXTRA FILES:**

**Comment by code2828** [comment]
Able to comfirm on 0.30-a0 local crawl (explore mode).
Game prints `Ran out of altars for temple! x3` on start. For 0.30-a0 the layout was a bit different but the bug persists. The temple is otherwise a normal one with 12 altars. See screenshots.

About to enter temple:
![截屏2023-06-18 上午11 29 02](https://github.com/crawl/crawl/assets/50510911/adeddf84-7990-45e5-a4a9-f3ca370c8a6f)

The temple:
![截屏2023-06-18 上午11 29 24](https://github.com/crawl/crawl/assets/50510911/68c0c74d-08a9-4354-9e71-5ee0779445b0)

Messages:
![截屏2023-06-18 上午11 29 36](https://github.com/crawl/crawl/assets/50510911/d77c5946-b825-46e9-91f3-b70a9ff5f483)

Char dump: [Character Dump](https://gist.github.com/code2828/4cab4eef80fe12ac54e3059556797a2b)

**Comment by projectNoob** [comment]
Another time.
<img width="1187" alt="image" src="https://github.com/crawl/crawl/assets/82269729/89480c6b-d943-411c-88ef-3972e845ad50">
version: 0.31-a0-859-g9dce7d3444 (trunk)
seed: 18443037326554722308
temple:
<img width="1187" alt="image" src="https://github.com/crawl/crawl/assets/82269729/86659c22-40c0-454e-9cc6-dd1c1ea74d14">

**Comment by NormalPerson7** [comment]
Just a couple of notes on this: firstly, I have seen this occur a few times when I was generating hundreds of wanderers for testing purposes. I could never actually find anything wrong with the dungeon, so I'm not sure if it actually has any impact on the game. The "Found twelve altars" message you refer to only reports those you discover in line-of-sight - this isn't a bug, it just looks a bit weird now that the temple is always fully explored on entry.
