### ISSUE TITLE
Odd EV behavior with Merfolk and flying over water

### ISSUE THREAD

**Issue by audreybeth** [crawl/crawl#2878]
**PLATFORM and OS or BROWSER:**
"local tiles" - Windows 10

**DCSS VERSION AND GAME INFORMATION:**
**DESCRIPTION:**
1) Character has 44 EV if I enter the water as a Merfolk (up from 36)
2) If I put on a hat with Fly and THEN fly over water, EV stays as 36
3) However, if I enter the water and THEN put on the hat with Fly, EV stays as 44 **forever** (armor is -1 because my helm with fly is +1 and my helm without fly is +2

**EXTRA FILES:**

normal EV:
![image](https://user-images.githubusercontent.com/7246695/207211976-ac239544-f6cb-4e94-bdbe-26e9296af090.png)

water EV:
![image](https://user-images.githubusercontent.com/7246695/207212033-981e7082-2e06-4ec1-b811-d206794e0fcd.png)

water EV with bug:
![image](https://user-images.githubusercontent.com/7246695/207212088-846bec59-e23f-4623-b9bc-5ee3690ace60.png)

Morgue: https://pastebin.com/b3pL6RxL

**Comment by riverfiend** [comment]
Does this ev upgrade remain if you leave the water?

**Comment by audreybeth** [comment]
Yes, remains after leaving the water

**Comment by Antern** [comment]
I guess, the only non-breaking solution is to cancel out the swimming form on activating FLY.

**Comment by edwinsage** [comment]
I think this is a UI bug rather than an actual game mechanic bug.  I'm noticing the same behavior with a flying merfolk, but if you bring up any menu, when you go back the numbers have adjusted themselves to what you would expect.  Additionally, movement speed while flying over water works as it should, being faster when starting movement on a water tile.  This is on CAO version 0.29.1-2-gbd0b4ee654 (console).

**Comment by semitonal** [comment]
Fixed, thanks for reporting! It was indeed just a visual issue, evasion should now redraw correctly.
