### ISSUE TITLE
No stairs to lower levels (Slime Pits)

### ISSUE THREAD

**Issue by megezuser** [crawl/crawl#2890]
So, it is in Slime Pits.
There is a stair (only one) from level 1 to level 2 and that's it.
And only one stair to go back from lvl2 to lvl1.
Seen on the screens.
Can't go for 15 runes then, have to start anew.
Never seen it before (hundreds of games played).

![Screenshot_1](https://user-images.githubusercontent.com/90180157/209133521-5859b2e9-a514-41a0-a60f-95fa0e16eefb.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/90180157/209133529-851eed17-73cc-4e79-8d86-96ca3c0d467e.jpg)

**Comment by rawlins** [comment]
Can you post a seed + exact version for this game (should be visible in the morgue for offline games)? Or a save file?

**Comment by megezuser** [comment]
Dungeon Crawl Stone Soup version 0.29.1 (tiles) character file.

Game seed: 13496993861895907359

**Comment by rawlins** [comment]
Thanks! On slime 2 there is a path to the rest of the level -- in the upper left of your screenshot, you can see one tile that has an unexplored area to the N, and this keeps going. This is still a builder bug because it shouldn't be possible to generate a path like that that only passes by slime walls, but not so bad as a complete lack of access.

Screenshot of that area with fully mapped slime 2:
<img width="758" alt="Screen Shot 2022-12-22 at 4 13 28 PM" src="https://user-images.githubusercontent.com/6290753/209227130-c15b18bf-3f10-4d47-ac2b-2fbb4456c262.png">

**Comment by megezuser** [comment]
Great, that's really a minor issue then.

**Comment by PleasingFungus** [comment]
Recent changes to slime walls have rendered this moot.
