### ISSUE TITLE
Arrival vaults rotated by mapmaker despite having the no_rotate tag

### ISSUE THREAD

**Issue by SergioJThompson** [crawl/crawl#2943]
**PLATFORM and OS or BROWSER:**
local tiles
macOS Catalina 10.15.7

**DCSS VERSION AND GAME INFORMATION:**
0.29.1

**DESCRIPTION:**
While testing arrival vaults in simple.des, I found that they are sometimes rotated vertically whether or not the no_rotate tag is specified.

In order to test a particular vault, I would sometimes add the heading PLACE: D:1, and sometimes WEIGHT: 5000 instead. I found that the rotation occurs whether either heading is added. I did not check whether it occurs when neither heading is added.

I tried putting the tags in different orders and the outcome was the same.

I've included screenshots of two maps that were vertically rotated despite having the no_rotate tag. The second map with the crudely drawn skull is my own, but the first map is not.

**EXTRA FILES:**

![pyramid_rotated](https://user-images.githubusercontent.com/72581976/212597436-b34a061e-0582-4ce0-8e89-49ac98726906.png)
<img width="1440" alt="skull_rotated" src="https://user-images.githubusercontent.com/72581976/212597439-a4683abc-922a-44fa-b68b-319b1c1c3860.png">

**Comment by nicolae-carpathia** [comment]
The map generator has other options to manipulate a vault's orientation besides rotation. It can also flip the vault horizontally or vertically. These two maps have no_rotate but not the no_vmirror tag (no vertical mirroring), so the map generator is fine with flipping them over top to bottom. The maker of onia_arrival_pyramid (presumably onia) forgot about mirroring, although I'm not sure the vault necessarily needs no_vmirror since the shape is somewhat abstract.

**Comment by SergioJThompson** [comment]
I see! I had overlooked that, thank you so much.
