### ISSUE TITLE
make ends on warnings or maybe also syntax errors

### ISSUE THREAD

**Issue by dchmelik** [crawl/crawl#2989]
**PLATFORM and OS or BROWSER:** Slackware64 GNU/Linux 15+current console (tiles next if this can be made to compile again)

**DCSS VERSION AND GAME INFORMATION:** 0.29.1

**DESCRIPTION:** make ends on warnings or maybe also syntax errors: [gist](https://gist.github.com/dchmelik/80c3a4f92c4a9ca44af664ea3c6cf050) log.

**Comment by rawlins** [comment]
Thanks for the report. The actual build error there is:

`Can't get version information: `git describe --tags` failed (no git, no repository, or shallow clone), and util/release_ver doesn't exist.`

This happens when attempting to build from a non-repository copy of the crawl repository (which unfortunately is what the default github zip download looks like), it can't get version info in this state. You could fix this by building from the repository, by hand-creating the file mentioned (with `0.29.1` in it), or preferably to the second, build with the official versioned source tarbell aimed at downstream packaging, which can be found: https://github.com/crawl/crawl/releases/download/0.29.1-debian/crawl_0.29.1.orig.tar.xz

(Because of the way the build process was done for 0.29.1, this file is in an obscure location for this version, but it'll hopefully be better named for the 0.30.0 release.)
