### ISSUE TITLE
Vhi's Electric Charge does not work through briar patches

### ISSUE THREAD

**Issue by Flugkiller** [crawl/crawl#3007]
**PLATFORM and OS or BROWSER:**
Webtiles

**DCSS VERSION AND GAME INFORMATION:**
0.30-a0-782-ge64f9170bb (webtiles)

**DESCRIPTION:**
When in range of an enemy that is behind briar patches, it still does not deem it a valid target for the spell. Not sure if this is intentional or not but I figured it was worth reporting just in case it isn't. Below is an image of a situation where this happens.

**EXTRA FILES:**

![chrome_2023-02-21_16-00-09](https://user-images.githubusercontent.com/59402112/220385116-7bbdd626-5755-40e3-8f2e-1988fe5dd4f4.png)

**Comment by PleasingFungus** [comment]
The issue here is that you *should* be getting the message `The briar patch is immovably fixed there.`, since stationary creatures (like briar patches) can't be teleported or blinked. You *can* get that message if there is a valid charge target *somewhere*:

![image](https://user-images.githubusercontent.com/1192475/235325121-5834c797-769e-428b-aa49-7e42c9a2c69c.png)

But if there aren't *any* valid charge targets, `electric_charge_possible` returns false and so `spell_uselessness_reason` just returns `you can't see anything to charge at.`

Really not sure what the right fix is. I poked at this a little bit, but it still won't give exactly the right message here, since it gets confused by the briars.
