### ISSUE TITLE
no "figurine of a ziggurat" generated at end of zigs after first

### ISSUE THREAD

**Issue by kscheirer** [crawl/crawl#3097]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
trunk
https://pastes.io/cbhfgsnlzn

**DESCRIPTION:**
At the end of first Zig (Zig#1) a figurine was generated as expected.
At end of second Zig (Zig#2) figurine was not generated. I thought I had done some something wrong by not clearing the final level.
Got new figurine from Tomb, at the end of third Zig (Zig#3) figurine was not generated. Char is on Zig27 now.

**EXTRA FILES:**
save http://crawl.akrasiac.org/saves/krsz-crawl-git-d936c97349-230421-0951.tar.bz2

**Comment by rawlins** [comment]
Thanks for the report! This bug was fixed (/cd70e7a56dcc) but saves that generated a zigfig before the fix are still affected. We're discussing how to address this; unfortunately with your char being on zig 27 already fixing the save in a sensible way is somewhat harder because it would involve regenerating the item. Were you hoping to do more zigs on this save?

**Comment by kscheirer** [comment]
I was hoping this would be my first mega-zig character :) But that is no problem, I will be satisfied with my first 15-rune win. Glad the bug is already fixed, thanks!

**Comment by PleasingFungus** [comment]
Going to call this resolved via cd70e7a56dcccdf43320cab26ac03874221abddd. Again, very sorry for the trouble.

**Comment by kscheirer** [comment]
No problem, bound to happen when playing in trunk! thanks for the support
