### ISSUE TITLE
No sound for offline dcss version 29,1

### ISSUE THREAD

**Issue by tmarc007** [crawl/crawl#3113]
<I tried to install an old sound file from 2010 but it doesnt work. There is no sound file for the game. please help. Thank you.>

**Comment by PleasingFungus** [comment]
I'm very sorry - Crawl's sound system has never really been supported.

You'll probably need to start by making a build with `SOUND` enabled, since the game might not default to having that enabled. (See https://github.com/crawl/crawl/blob/master/crawl-ref/INSTALL.md#compiling for compilation instructions.) Good luck!
