### ISSUE TITLE
Review text at the end of tutorial is rendered with html tags intact (and thus without colors/styling)

### ISSUE THREAD

**Issue by random-cdda-modder** [crawl/crawl#3168]
**PLATFORM and OS or BROWSER:**
local tiles, linux

**DCSS VERSION AND GAME INFORMATION:**
0.30

**DESCRIPTION:**
Review text at the end of tutorial is rendered with html tags intact (and thus without colors/styling). Screenshot is from first tutorial (movement) but all tutorials have the end review with html.

**EXTRA FILES:**
![Screenshot from 2023-06-18 21-38-17](https://github.com/crawl/crawl/assets/128377542/b2150e43-2d80-474d-98ff-90d4180f80dc)

**Comment by temporaryMan1233** [comment]
[Culprit commit](https://github.com/crawl/crawl/commit/8e7229f42b641c003bf5ab767e04083e393a620f)

**Comment by temporaryMan1233** [comment]
Actually, just removing [the `replaceAll` call](https://github.com/crawl/crawl/commit/8e7229f42b641c003bf5ab767e04083e393a620f#diff-5345c5d353611eca32314199a120e9a1f6272b05b23df2faee8be1360cd39a0cR71) fixes this issue.

This call escapes styling tags so they are displayed as is instead of being rendered. I was wondering why escaping tags is necessary here (probably necessary if we want to display `<` itself to the player?).

The comment suggests we relax escaping a bit, and I agree. I think it is better to intentionally escape stuff in the message text itself, just like we do when we escape backslashes, for example. That's more explicit and less error prone.

**Comment by PleasingFungus** [comment]
@rawlins , maybe take a look at this when you have time? (If you don't, I can look later.)

**Comment by temporaryMan1233** [comment]
This issue is fixed in trunk ([commit](https://github.com/crawl/crawl/commit/b41548654ea1899)).

**Comment by PleasingFungus** [comment]
Thanks!
