### ISSUE TITLE
hearing a distant slurping causes the game to forget the most recent player action

### ISSUE THREAD

**Issue by krehera** [crawl/crawl#3194]
Firefox on Windows
webtiles version 0.31-a0-246-g8cbcc1cb85 played on Kelbi

**DESCRIPTION:**
I like to use the ~ command (repeat last action) a lot but doing that as a follower of Jiyva is difficult -- any time I heard a distant slurping, I forgot what I was doing! The game would then say no last action to repeat.

**Comment by PleasingFungus** [comment]
Good bug. This is caused by the implementation of Jiyva's off-level jelly eating behavior (which unloads the current level, loads other levels, changes them, and then reloads the current level). We should probably replace that.

See also https://crawl.develz.org/mantis/view.php?id=9561 , which could be related.

**Comment by rawlins** [comment]
> Good bug. This is caused by the implementation of Jiyva's off-level jelly eating behavior (which unloads the current level, loads other levels, changes them, and then reloads the current level). We should probably replace that.
> 
> See also https://crawl.develz.org/mantis/view.php?id=9561 , which could be related.

This is possibly still an issue but the one I was able to replicate (which was very easy to do and has a very frequent effect on a level with high jiyva piety) is simply from a bug in how item stacks are reduced, so I marked this closed.
