### ISSUE TITLE
Transforming over water does not function as intended.

### ISSUE THREAD

**Issue by Monkooky** [crawl/crawl#3274]
Transform.cc line 257 features code which should display the message 
"As you dive into the water, you transform into \<form desc\>" when previously flying, entering water, and able to swim. 
I tested this with storm form into various forms, and with artefact armour permitting flight into various forms. I tested with both Barachi and Merfolk, both of whom can swim. I was unable to find a way to generate the 'As you dive into the water... " message, and cannot identify why it is failing. 

Notably, Blade Hands overrides this function and even were it fixed in general Blade Hands would be an exception.

**Comment by pooka109** [comment]
I've looked at this, using a merfolk in storm form transforming into flux form. (I don't have a solution, but maybe the information is useful.)

In that case, the "As you dive into..." message doesn't show up because, in transform.cc:Form::transform_message(), the "get_form(previous_trans)->player_can_fly()" check returns false, because previous_trans is transformation::none. If I understand it correctly, and given that I'm transforming out of storm form, previous_trans should be transformation::storm here, not transformation::none. Another indicator that something is wrong is that when transforming directly from storm form to flux form over deep water, the flux transformation message "You turn into something dangerously unstable." doesn't appear.
