### ISSUE TITLE
Dump bug

### ISSUE THREAD

**Issue by pyy156941** [crawl/crawl#3345]
**PLATFORM and OS or BROWSER:**
Windows 11, Microsoft Edge, CKO

**DCSS VERSION AND GAME INFORMATION:**

0.31-a0-997-g9a2f3ffc92 (webtiles)

**DESCRIPTION:**

In my char dump, 
```
 15721 | Elf:1    | Identified the  "Udeicali"
 15721 | Desolati | Identified the  "Leim"
 15721 | Desolati | Identified the  "Yntan"
 15721 | Elf:1    | Entered Level 1 of the Elven Halls
```
I suspect this is incorrect. 
Dump: [Dump](https://paste.ubuntu.com/p/hkBS7sh5b7/)
**EXTRA FILES:**

**Comment by rawlins** [comment]
Thanks! This replicates easily, e.g. Lair 5 on seed 1 in current trunk. What seems to be happening is that during level building, partially generated randart books get fully id'd, at a point where the object isn't fully constructed (the name printed isn't even necessarily final I think, in the seed 1 case I checked with a debugger the book is identified as `the  "Amolul"` but gets an actual name of `the Compendium of the Incendiary Hornet`).

The issue seems to come from 85e71fe22c973af5, specifically the call `set_ident_flags(book, ISFLAG_IDENT_MASK)`: `set_ident_flags` -- that function triggers a note call on full id of a randart. I can see some possible quick fixes, but I'm not sure of what a really good fix for this is (since id code like this is clearly assuming it is being triggered by player actions only, and maybe needs some rethinking if that's not going to be the case).

As a further bug, this will probably prevent a note when the player encounters the actual artefact.

**Comment by PleasingFungus** [comment]
Hopefully fixed, thanks!
