### ISSUE TITLE
Using Autopickup menu button \ crashes Android

### ISSUE THREAD

**Issue by ZodachGonger** [crawl/crawl#3490]
**PLATFORM and OS or BROWSER:**
Android

**DCSS VERSION AND GAME INFORMATION:**
31.0

**DESCRIPTION:**
I cannot use the \ button to launch the toggle autopickup menu without the game crashing. 

**EXTRA FILES:**
[crash-Dragoon-20240125-214903.txt](https://github.com/crawl/crawl/files/14060478/crash-Dragoon-20240125-214903.txt)

**Comment by robertxgray** [comment]
This bug is a pain because the debug builds are not affected by the crash. I have just proposed a fix after lots of testing, but I don't have a good explanation for this. I guess it's related with accessing a non existing element the Gem_prop array, but all the other builds are okay with this.

**Comment by rawlins** [comment]
> This bug is a pain because the debug builds are not affected by the crash. I have just proposed a fix after lots of testing, but I don't have a good explanation for this. I guess it's related with accessing a non existing element the Gem_prop array, but all the other builds are okay with this.

Were you able to get a more complete stack trace for this crash?

**Comment by robertxgray** [comment]
No, but I added debug logs everywhere and was able to track the crash point until invent.cc:89

```
81  if (in_inventory(i) && i.base_type != OBJ_GOLD) 82  {
83      // We need to do this in order to get the 'wielded' annotation
84      // We then toss out the first four characters, which look
85      // like this: "a - ". Ow. FIXME.
86      text = i.name(DESC_INVENTORY_EQUIP, false).substr(4);
87  }
88  else
89      text = i.name(DESC_A, false);
```

**Comment by ZodachGonger** [comment]
The update works! Thank you!

**Comment by robertxgray** [comment]
> The update works! Thank you!

To put this into context, I've uploaded a new version to Google Play including #3493.

F-Droid gets the source from the main repo, so I'll update the version when we have this or an alternative fix merged. F-Droid users are still on 0.30.1, so they're not affected by the bug.

**Comment by rawlins** [comment]
Looked into this a bit more; as of bec6b6ccbf85, which should be present in 0.31.0, `NUM_GEM_TYPES` is the correct item type for generic "gems" and 0 will print the wrong thing in the known item menu. 0 will definitely prevent this crash but it's just hiding a bug somewhere in the item name code (I assume). Would it be possible for someone to check if any of the `ASSERT`s I added in 04fe69798e6f trigger as part of this crash on the relevant android builds? This unfortunately doesn't replicate on macos on any build I've tried.

(Looking into tagging 0.31.1, we definitely want a fix for this in it.)

**Comment by robertxgray** [comment]
Oh my! I spent the whole afternoon trying to make the game crash in vain. I guess there was some unknown problem in my build setup and now it's fixed. Thank you for your time and sorry for the trouble. 

Some of the tests were made using the version with the asserts. No problems.

> 0 will print the wrong thing in the known item menu

Actually, this is the current behaviour, because _tileidx_gem_base returns GEM_DUNGEON by default. It has little impact because they're similar.

```cpp
2679    switch (item.sub_type)
2680    {
2681    default:
2682    case GEM_DUNGEON: return TILE_GEM_DUNGEON;
```

![imagen](https://github.com/crawl/crawl/assets/9676118/9a46addf-f41c-4318-8e73-dc0a7f3f826b) GEM_DUNGEON
![imagen](https://github.com/crawl/crawl/assets/9676118/585955bf-47ad-4bdf-9166-e7adf4a5b84e) GEM_GENERIC

Also, isn't GEM_GENERIC a bit misaligned in main.png?

![imagen](https://github.com/crawl/crawl/assets/9676118/b7886d51-3829-4ceb-9915-82f383672e77)

**Comment by wheals** [comment]
So can this issue be closed?
