### ISSUE TITLE
Death message for Usk on trunk suspect.

### ISSUE THREAD

**Issue by eadsjr** [crawl/crawl#3545]
**PLATFORM and OS or BROWSER:**
webtiles

**DCSS VERSION AND GAME INFORMATION:**
trunk (>0.31)

**DESCRIPTION:**
Bug: On trunk, on death, Vampire Enchanter of  Uskayaw gets:
```
You die...
<Uskayaw death corpse>
```

**Comment by pooka109** [comment]
After some checking, it's only happening with undead (i.e. exsanguinated) vampires.

It's setting up the proper extended key of "Uskayaw death corpse undead", and, in godspeak.txt, that points to "<Uskayaw death corpse>".

But "<Uskayaw death corpse>" is supposed to be replaced with the text under the extended key "Uskayaw death corpse", in order to get the proper result "Your body falls in perfect tune with the rhythm.", and that's somehow not happening under these circumstances.

**Comment by pooka109** [comment]
And the same problem happens with Gargoyle Enchanters of Uskayaw.

In that case, it's setting up the proper extended key of "Uskayaw death corpse nonliving", and, in godspeak.txt, that also points to "\<Uskayaw death corpse\>".

The text replacement is not happening here, either.

**Comment by pooka109** [comment]
This should be fixed now.

For the record, the speech substitutions were supposed to be "\@Uskayaw death corpse\@" and the like.
