### ISSUE TITLE
Undead (Mummy) allowed to equip holy wrath weapon

### ISSUE THREAD

**Issue by Wahllhala** [crawl/crawl#3629]
**Windows 10 OperaGX webtiles**
opera LVL5 (core: 107.0.5045.60)

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-630-g46d191b0ed

**DESCRIPTION:**
I simply started a new as a mummy, found a whip of holy wrath on D1.
The whip wasn't grey out like useless item but displayed liked standard
usable branded weapon. Picked it up to check if I could use it, I could.

Brand description says I should not be able to do so as a mummy, but
I admit I didn't check the changelog to see if it got a rework.

**EXTRA FILES:**

**Comment by pooka109** [comment]
Behavior in trunk, by that version, has changed so that you can wield holy wrath weapons, but their holy wrath effect won't work for you, and they'll act like ordinary weapons in your hands.

When you wielded the whip, there should have been a message that "it sits dull and lifeless in your grasp" instead of "it softly glows with a divine radiance". That's the sign.
