### ISSUE TITLE
Evoking a talisman on the floor does not pick up the talisman

### ISSUE THREAD

**Issue by hbent** [crawl/crawl#3639]
**PLATFORM and OS or BROWSER:**
local tiles, MacOS 10.14, local build of current git sources

**DCSS VERSION AND GAME INFORMATION:**
0.32-a0-658-g9eff4c5b6e

**DESCRIPTION:**
Evoking a talisman, in this case a beast talisman, on the floor does not pick up the talisman.  The transformation occurs but without the talisman in your inventory there appears to be no way to undo the transformation!

**Comment by pooka109** [comment]
Evoking a talisman on the floor when transformed will still properly untransform you.

**Comment by hbent** [comment]
Sure, but why wouldn't you want the default behavior to be to pick up the talisman?  Without it in your inventory, you can't untransform unless you're at the exact location of the talisman, which seems entirely unintuitive.

**Comment by pooka109** [comment]
Some other items you can use from the floor don't get picked up when you do so, either, such as scrolls and potions. Weapons and armor do, but only because you can't wield weapons or wear armor without their going into your inventory in the process. (Although I have noted that evokables other than talismans, such as wands and boxes of beasts, can't be evoked from the floor, which does seem odd.)

More importantly, if your inventory's full, picking a talisman up from the floor when you evoke it won't be possible anyway, which is why using things from the floor is an option in the first place.

**Comment by hbent** [comment]
Of course scrolls and potions wouldn't get added to your inventory - they're single use items, and you're using them up before they have a chance to be added to your inventory.  The other evokables you mention probably should be able to be used from the floor, and I would argue that they should attempt to be added to your inventory if possible, though their nature doesn't require that.  Because talismans are a continuous use item, I would think that they should be added to your inventory if possible, and only left on the floor if your inventory is full.

**Comment by pooka109** [comment]
Talismans are not really a continuous use item; you can evoke one to change form, and then drop it somewhere, and your form won't be affected, so it doesn't have to be in your inventory to keep working. And if you need to change back, and can't reach it for whatever reason, you can find another talisman, evoke it to change to its form, and then evoke it again to go back to your original form.

More generally, making talisman pickup after floor use the default behavior will cause problems for players with full inventories, and they'll mostly be the ones using items from the floor anyway, which will cause worse problems. Making it an optional behavior is redundant, since you can just enable autopickup of talismans, from the "\" screen or similar, to accomplish that.

I'll grant that it's unusual, but it's not a bug or unintended behavior. If staying in a given form actually required you to keep that form's talisman in your inventory, things would be different, but that's not the way they currently work. You can just pick up the talisman off the floor after using it from there, either manually or with autopickup. And if your inventory's so full that you can't hold the talisman in your inventory afterward, you either need to manage your inventory better, or properly keep track of wherever your talismans are in the dungeon.

**Comment by pooka109** [comment]
No problem. And I was mistaken about one thing: there is an untransform option in the ability menu, in case you're transformed and don't have a talisman handy.
