### ISSUE TITLE
[Feature Request]Let Draconians train Armour skill

### ISSUE THREAD

**Issue by projectNoob** [crawl/crawl#3847]
Draconians can wear cloaks and boots, whose effectiveness is affected by Armour skill (not much, but anyway it is).

**Comment by NormalPerson7** [comment]
The maximum base AC you can have on a draconian is 3, meaning 27 armour skill gives a bonus of +3.68 AC. While it's likely true that the first 5 or so skill levels may be worth training because they're so cheap, beyond that, there really would be no point training armour skill unless you had literally nothing else helpful to train.

Armour skill is therefore nearly useless for draconians and we don't want to encourage training it. Hence, they're banned from doing so.

**Comment by DracoOmega** [comment]
Yes, there is no intention to change this at this time.
