### ISSUE TITLE
Help lookup for transmutation status indicators (in ?/T)

### ISSUE THREAD

**Issue by evktalo** [crawl/crawl#393]
Transformation status lights don't have descriptions in ?/T look-up. I was just porkalated by Pikel with a polymorph wand, and it wasn't immediately obvious what I would be able to do, so I tried to look the Pig status up - but there's no helpful description text for it there. Hence, this issue:

1. Figure out what are the transmutation statuses, particularly the negative transformations monsters inflict on the player (for the transmutation spells, there already are spell descriptions)
2. Figure out how they affect the player character
3. Write informative descriptions of the statuses (what would a player want to know) in dat/descript/status.txt

**Comment by nagdon** [comment]
I wrote some status descriptions for the negative transmutation statuses (Bat, Pig, Tree, Porc, Wisp and Fungus), they are in the following text file:
[polymorph_status.txt](https://github.com/crawl/crawl/files/601724/polymorph_status.txt)

These descriptions are much longer than the average status effect description, but I think that this is almost unavoidable, because transmutations have lots of different unrelated effects and each of them may be important. If these descriptions are usable, then I can easily write similar descriptions for all other transmutation status effects.

Remark: I collected the effects of the transmutation statuses by reading transform.cc and form-data.h again (I already read them a few years ago when I wanted to solve some bug) and then grepping for the TRAN_XXX constants corresponding to the status in question. I think it is unlikely that I missed any important effect of these statuses (I omitted some very minor interactions for the sake of brevity, e.g. that Tree form prevents floundering in shallow water).

**Comment by MarvinPA** [comment]
I actually ended up tweaking and removing a lot of the tiny trivial effects in the process of documenting these myself (and was unaware this issue existed when doing so, apologies for the duplicated work!). I'd missed documentation on the XL-based melee attacks though, thanks!
