### ISSUE TITLE
Shafting can place you into transporter vaults.

### ISSUE THREAD

**Issue by kuniqsX** [crawl/crawl#4088]
Webtiles trunk as of October 14.
https://underhound.eu/crawl/morgue/kuniqs/morgue-kuniqs-20241014-102022.txt
![a](https://github.com/user-attachments/assets/595d29a8-156d-42cf-9c18-3d0968bf6fb1)

**Comment by kuniqsX** [comment]
Exploration trap shaft to be specific, sorry.

**Comment by kuniqsX** [comment]
Can't prove it but seems to me like the game tried to find a patch of land free of enemies in LOS, failed, and rolled this outcome. Could be the code responsible for placing you in such circumstances doesn't exclude vault tiles.
That, or this vault in particular doesn't exclude its tiles from being eligible for shafting.

**Comment by Implojin** [comment]
Hi, thanks for the report (and the reddit thread)!

I took a look at the relevant code and as far as I can tell there isn't actually a bug here: Our ghost vaults and our player shaft check all appear to be appropriately respecting `no_tele_into`.

The issue here is that this isn't a ghost vault: It's just a float vault with a transporter. (This vault is `gammafunk_sealed_arena`.)

Historically we've reserved `no_tele_into` for very extreme vaults, and while this vault is maybe borderline (it can spawn an OCS sometimes!), it's currently intentional that this vault doesn't have `no_tele_into`.
