### ISSUE TITLE
not work "you.one_time_ability_used" on okawaru

### ISSUE THREAD

**Issue by FireBladeVortex** [crawl/crawl#4105]
**PLATFORM and OS or BROWSER:**
Graphical Tiles download

**DCSS VERSION AND GAME INFORMATION:**
okawaru gift rework in 0.31 0.32 0.33(trunk)

**DESCRIPTION:**
always got false
without used or not used (both weapon and armor)

**Comment by DracoOmega** [comment]
While it's a little unclear from this report, if you're talking about querying this property from lua, Okawaru's gift abilities do not use or set this flag (since there are *two* of them). As someone who never uses clua personally, I'm not certain how much benefit there is to setting the flag once they've both used, entirely for querying purposes; would welcome a second opinion.
