### ISSUE TITLE
Wu Jian auxiliary attacks under Serpent's Lash in Dragon form can miss.

### ISSUE THREAD

**Issue by kuniqsX** [crawl/crawl#4121]
Trunk, webtiles.
Not sure if it's intended behaviour:
![abcde](https://github.com/user-attachments/assets/67901112-f73a-47b5-87b2-263b487ba850)

**Comment by Implojin** [comment]
To me, this looks intended: Serpent's Lash specifies that it causes "martial attacks" to never miss, and we're consistent in-game (and in the code) about WJC's martial attacks being whirlwind, lunge, and wall jump. In your screenshot, all of the martial attacks look like they've successfully hit. Auxes are auxilliary attacks with their own separate to-hit rolls, and that's expected behavior.
