### ISSUE TITLE
Tukima's Dance used on dual-wielding monsters bug re: sprite appearance.

### ISSUE THREAD

**Issue by Ash-R** [crawl/crawl#858]
Platform: Webtiles
Version: Trunk, 0.22

Using Tukima's Dance on dual-wielding monsters such as two-headed ogres or ettins occasionally causes both weapons to disappear from the monster sprite, but upon inspection the game will note that they are still wielding a single weapon and by casting Tukima's Dance a second time this "invisible" weapon can be animated as normal. All seems to be fine with the code apart from the sprite appearance.

Edit: Added screenshot example.
![tukimasdancespritebug](https://user-images.githubusercontent.com/7052761/46581399-cc2fa080-ca83-11e8-88b6-fee40775c07d.PNG)

**Comment by stenellad** [comment]
This bug involves the interaction between [_animate_weapon](https://github.com/crawl/crawl/blob/master/crawl-ref/source/spl-summoning.cc#L797)  and [mcache_monster](https://github.com/crawl/crawl/blob/master/crawl-ref/source/tilemcache.cc#L226).

When _animate_weapon calls target->weapon() in its second line, it chooses between the first and second weapon at random. If it chooses the first weapon, the bug occurs. If it chooses the second, everything looks normal. 

//Speculation
This is due to dual-wielding monsters' second weapons being placed in the "shield" attribute. When a primary weapon is removed, the secondary weapon is moved to the primary slot, but the cache is not updated.
