### ISSUE TITLE
Music for Crawl

### ISSUE THREAD

**Issue by ghost** [crawl/crawl#913]
Hello,

We are a duo of musicians who want to contribute to DC by writing ambience/music for the game.

From what I gathered from IRC, there is currently no proper sound engine for the game, so any music we would write would depend on the implementation.

There is a couple of issues that arise and several ways to do this:

Issue #1: Proper large loops will have a huge size to download
Issue #2: The typical gameplay session is very long and music needs to be designed in such a way as to not be annoying.

So there are a couple ways from musical point of view to do it:

1) MIDI (Limited sounds, very small size, doesn't sound that good)
2) Proper Mp3/Wav loops (Huge size, might get annoying)
3) Small Loops/Stingers

The best way to do it as I see it is to create several small loops and stingers. Examples: Loops of water dropping/small wind blowing; Stingers for going into a new area; Stingers for finding lairs of uniques (After you see them, to avoid any difficulty decrease); Stingers for finding good loot; Stingers for low health; and so on.

Since DC doesn't have a proper music system implemented, the way we do music will depend if and how the music systems are implemented. Having 50-100 loops of around 5-15 seconds should be only 15-30 Mb in size, and can be offered as a separate package.

So if any of the devs are willing to work on this, we are willing to provide the music. We are open to suggestions, and as long as technical side is done we are willing to do pretty much anything that isn't TOO crazy.

Thank you for reading, and I hope we can hear from you guys, thanks for the good work!

Ivan.

**Comment by stenellad** [comment]
Do you have ideas regarding where you want to put what? e.g. "We want to make one track for Dungeon, one track for Lair, etc."

**Comment by TheTerribleI** [comment]
Well, once again, that would depend on the general implementation. If its 50-100 loops, those can be used throughout, with a few of them being exclusive.

If we had to write proper soundtrack (From what I gathered from IRC not everyone would agree to that), I would do 10-20 minute Dungeon soundtrack (Maybe escalating a bit depending on the depth?), and 5-10 minute ones for other areas (Approximate time, obviously if needed can be extended).  There would probably be some moments of silence in between (3-15 minutes? depending on how active the tracks are), so they won't be grinding on peoples nerves.

If we are doing smallish loops, then I would imagine about 20-25 of them would go towards general dungeon events (Vaults, Uniques lairs, Entering new floor/section; so on); 20-25 would go for general events (Good loot, running low on health/dangerous fight/hungry;Misscasts and such).  The rest would go into ambience of individual areas (Maybe some nature sounds for Lair, some "Undead" like sounds for crypt and so on).

Hope this answers your question; We can figure out a more precise numbers once we know what kind of sound/music we are doing.

**Comment by minqmay** [comment]
I would strongly recommend using a [module format](https://en.wikipedia.org/wiki/Module_file) instead of MIDI. The skills for making MIDIs transfer fairly easily to using mod trackers - some of them even let you import MIDI files - and you get the same advantage of small filesizes, but mod formats are capable of much more.

**Comment by ebering** [comment]
Hello! Thank you for your interest in contributing. While it is currently more focused on the gameplay side of things, the [contribution guide](../blob/master/crawl-ref/docs/develop/contribution-process.md) should help acquaint you with the outline of what to expect. This issue is a good place to keep the conversation organized.

I have some thoughts, which will follow, but I want to start with the disclaimer that I don't think I'll have time in the 0.23 cycle to invest in the sound system beyond listening and testing. These thoughts break down into three parts, the [technical part](#technical-challenges), the [community part](#community-considerations), and the [aesthetic part](#aesthetic-considerations).

**Summary:** The current crawl sound support should probably be scrapped in favor of something that makes use of ui-overhaul; to do that you'll need to find someone to handle the software side, be that a devteam member or community contributor. Since technology is something that you indicate will have a major impact on the creative direction and on the tools and formats used, I recommend you do that first.

## Technical Challenges

### The current state of crawl sound

Crawl can be compiled with the `USE_SOUND` option. This enables the rudimentary sound system in [sound.cc](../blob/master/crawl-ref/source/sound.cc). The sound engine there is sent every message printed to the message log, via parse_message, as a string. This string is then matched against a regex (the list of mappings configurable in the options file) to find the filename of a wav file, which is played via one of windows multimedia, a compile-time specified command line command, or SDL, depending on the compile configuration.

I have not tried compiling with this option, I don't know if it actually builds and works as documented.

Webtiles as shipped does not have sound support, however the webzook.net server has local patches which provide some web tiles sound effects I believe. @sesangsokuro (the admin and maintainer of those patches) would be able to explain more about how they work.

Can this be scrapped and replaced? Probably. Definitely if it doesn't actually build. If it does build we will want to reach out to users and see if anyone is using this feature for accessibility reasons before scrapping it, and make sure that the replacement meets their needs. Did you know that there are people who play crawl with a variety of adaptive devices?

### Where to play the sounds and where to trigger them in the game code.

Crawl has 3 user interfaces: console, local tiles, and web tiles. A lot of work was done in 0.22 to unify the user interface abstractions, and a new sound engine should make use of this work to produce a ui agnostic abstraction to be used for scheduling sound events. @aidanholm will know more and is a good person to ask about crawl ui in general.

### What dependencies are introduced.

For local tiles, SDL already supports a ton of formats. I'm not sure if there are local console players that will want sound and be unable or unwilling to build with SDL, so SDL can probably be used there without fuss (as it can be for the current sound system). Webtiles will depend on browsers and that's a whole can of worms I know little about. However, if web tiles isn't supported a large chunk of players will never experience sounds.

### Size

@minqmay has suggested a format and approach that produce small files, but I don't know what the state of browser support for MOD formats is. Size is important for keeping our distribution small, but also if web tiles is targeted for not destroying the bandwidth of our server hosts. There might be web-scale engineering tricks to alleviate bandwidth pressure (using Amazon S3 or other object storage) but they'd require someone to come forward and support the hosting long term. @alexjurkiewicz might know more.

### Development

As I mentioned above, I will not be able to lend a hand with this project in the 0.23 cycle. The current crawl sound engine is probably not what you want to use (though if you want to make some sonic prototypes/drafts and it works it could be workable). So you need a developer. Other team members might be interested, I don't know. You could also engage with a software-savvy community member to collaborate on the project, but please have that person get in touch with us before they dive in so we can discuss the technical design (how the previous questions are addressed &c.) with them.

## Community Considerations

DCSS owes its vibrancy to a long list of community contributors. This goes for all aspects of the game, and my hope is that it would be able to be true of an eventual soundscape also. To enable this, I'd like to see any sound submission satisfy the following in the final draft. (Point 2 requires some advance planning, Point 1 might change your mind about the project, Point 3 is a last step).

- CC0 licensing, like our tiles.
- A common format that is easy to edit and remix with free (take your favorite definition, preferably free as in freedom) software widely used in the community.
- A guide to creating, editing, and adding sounds to the game like [the one for tiles](../blob/master/crawl-ref/docs/develop_tiles_creation.txt).

## Aesthetics

This section was going to be me rambling about the music I like to listen to while playing crawl. That's not helpful. However I'll mention here that you'll probably get resistant feedback from whichever of the following fan groups you spurn in your composing

- Metal
- Chiptune
- Electronic (but more bits than chip tune)
- Classical

My advise here is (if you decide to do this): make what you desire at the best quality you can. Well done work that you enjoy doing will be better than trying to please everyone.

The one aesthetic guideline that, if you compose something, I'll insist on, is that the Zot sounds must be *absurdly bizarre*.

**Comment by minqmay** [comment]
When using module formats for a video game, the game's entire soundtrack is typically put into a single mod file so that all the songs can share samples. Then it can also be compressed with mo3 ( https://www.un4seen.com/mo3.html ). The author of mo3 has mentioned in the past that he may be willing to release the mo3enc / unmo3 source under the GPL; I could ask him about that.

HOWEVER, if you are not familiar with tracking then it's probably not worth the extra effort to learn it. I mainly mentioned it because it is a much better option than MIDI ;p

**Comment by TheTerribleI** [comment]
Yeah, we just compose in Ableton mainly. If there is a demand we could learn tracking, but as you said, easier not to.

**Comment by TheTerribleI** [comment]
^Honestly I only agree with third point

1) Wav/OGG formats as well as DAW software are well-established and unlikely to have any major compatability changes at any point in the future (I.e any audio-working station will always support audio stems). Supplemented by MIDI data, where needed it gives pretty much the same result.

2) Same as above - Stems can be imported and uploaded and easially accesed. Anyone who ever used any audio software  can cut a sample out of a stem.

I would even argue that more people have experiences with traditional DAWs that they do with the trackers- making a tracker format audio less accesable than a standart wav/ogg/mp3 one.

However, there is no point into looking into that right now- an audio engine must be made first. The implementation will depend on whoever decides to write it - so if that person decides to make support of a tracker format over traditional codecs - we are all game, it will just take us a little bit (a while?) longer to write the soundtrack.

**Comment by Rydian** [comment]
>     2. Same as above - Stems can be imported and uploaded and easially accesed. Anyone who ever used any audio software  can cut a sample out of a stem.

Stems as in the format with the individual instrument tracks, right?  While having them in the source/game does cut out issues where snippets of one instrument combine with different instruments, it doesn't automatically give a single "pure" sample (for easy transposing and copying out) that always avoids being modified by the existence of other samples in the same track (blending in/out, reverb from a previous play, stuff like that).

Also, from what I'm reading the stem file would duplicate data by having the individual tracks alongside the pre-mixed one, which would _inflate_ the filesize (whereas a tracker format would be much smaller while still giving access to the samples used without interference from other instances).  As well the FAQ for the format only defines 4 instrument tracks (plus a pre-mixed result as a fifth), another limitation to deal with.


> I would even argue that more people have experiences with traditional DAWs that they do with the trackers- making a tracker format audio less accesable than a standart wav/ogg/mp3 one.

The modern operating systems most people use come with neither fancy multi-track audio editors or tracker format editors, so users will have to install one of their choice from some location.  There's a variety of software for both formats easily available online, so I'd say the accessibility of both is the same.

To be a bit less pedantic... _the learning curve_ will differ depending on the software and the user's prior experiences, but we _are_ talking about something to contribute to a game development project, and (somebody correct me if I'm wrong) I think many development decisions made here assume that contributors have at least a basic working grasp of the formats and tools involved in whatever they'll be editing.

I've dealt with various audio formats one way or another over the years.  Waveform, mod, console chip, MIDI, even _text-based notation_ like MML.  Various ways to store and play back audio/music have their upsides and downsides, and various formats are generally chosen based on how well what they offer fits the needs of the program they're meant to be used by.

I believe that Crawl could benefit from a tracker format primarily for the ability to edit _and expand upon_ the composition it provides (as in future years completely unrelated people might be working on it), and secondarily for keeping file sizes lower for server owners and both offline and online players (and perhaps port maintainers but they're generally on their own anyways I guess).

**Comment by rawlins** [comment]
It's possible that if the question were, in the abstract, "what kind of a music engine should crawl have?", then the answer, all things equal, could be some kind of mod-like format. (Though to be clear, I am not in favor of this.) However, this particular issue, though raised in a relatively neutral way, is not actually this question in the abstract. Rather it's someone volunteering to do an awful lot of work who has no prior experience with trackers. If we (the devteam) are to accept this offer, speaking as a hobbyist musician myself, I think imposing a new format like this would be a major handicap to the project.

>As well the FAQ for the stem format only defines 4 instrument tracks (plus a pre-mixed result as a fifth), another limitation to deal with.

While there does seem to be a specific audio format using the word "stem", I doubt that's what was being referred to here, as "stem" is a general term for unmixed audio tracks, usually that collapse by certain categories (e.g. drums, vocals, leads). See [e.g. here](https://www.izotope.com/en/blog/music-production/stems-and-multitracks-whats-the-difference.html).

**Comment by TheTerribleI** [comment]
@Rydian Stems can be uploaded separately, for remixing purposes. There is no reason to keep them in the soundtrack. Also im refering to stems as individual files, not formats. I.e you have a pad and a kick - you upload separate track of a pad and a kick. You can upload stem for every instrument you have playing/groups/returns (reverbs and such) and what have you. You can simply keep those for remixing purposes somewhere on the server, even dropbox, they don't have to be included by default with the soundtrack.

Not to mention that while yes, operating systems don't come with fancy editors, 95% of musicians never worked with trackers, while 100% of them worked with some sort of audio manipulating software.

But yeah as @rawlins said - we would strongly prefer to not do the tracker format simply because we are really experienced at what we are doing currently- so an hour or so of soundtrack we can probably complete in 2-3 weeks, if not less. With trackers it would take us 2-3 weeks to get used to it and assemble a pack of samples to begin with (or at least convert them) and make sure our plugins work correctly with the new software. If devs decide to go with that, that's fine, more experience under our belt, its just the production isnt going to be nearly as smooth from our side.

**Comment by Rydian** [comment]
> 95% of musicians never worked with trackers
I might be jumping to conclusions here... but I believe you may have some misconceptions.  You may be thinking tracker formats are a niche thing only used for some sort of hobbyist scene, but in terms of game development... Final Fantasy _4 through 10_ (and various spinoffs and other entries) used tracker formats internally for their music, for example.

Not to mention _almost every single game ever released_ for the SNES, GBA, N64, DS, PSX, and other systems I'm not technically familiar with.  Even when systems started storing games on larger-capacity media and could handle normal audio files (like the PS2 using discs), many games for systems like the PS2 still used tracker formats for their music, sometimes alongside normal audio for special things like when vocals were needed (or for FMVs or recordings of real bands for sports/racing games).  Final Fantasy 10 for example had the majority of its music tracks in a tracker format.

-----

Anyways, _if_ unmixed tracks _and samples_ were in with the source and only the final mixed things were in the distribution that would be a lot better.  If that type of operation continued to be maintained by future contributors it would make expanding on previous works easier too yeah.

**Comment by ebering** [comment]
@TheTerribleI a quick note as you process feedback here, people marked "Member" are members of the development team, and "Contributor" are community members whose contributions have been merged into the repository.

If it is the case that sticking with MIDI (which if I understand the above meets the remixing requirements as long as some extra stuff is included in the source) makes composing on your end much much smoother, then as @rawlins points out that's the best course of action. It won't be the first time that a technology decision for crawl has been made based on what a volunteer contributor is comfortable with. I was not aware of the difference in effort the format change would make. Compression or mastering would add some kind of encoder to the build process, but we already do this with png optimization for tiles, and it's not a large technical hurdle.

My bigger concern is that you haven't yet found someone with time to commit to developing. I've pinged a few people who might be interested, I hope they'll appear and get in touch with you.

**Comment by ebering** [comment]
@Rydian Thank you for your enthusiasm for our project, and your concerns about the long term edibility of the formats. Like many technical decisions of crawl's architecture, what someone is willing to do now has a big influence. For example, the choice of Tornado as the web server for crawl WebTiles was made, as far as I can tell from the old mailing list, because that is what Florian used to write the initial prototype.

As far as providing the necessary components to remix and revise the soundtrack goes, I think everyone is on the same page on that.

**Comment by TheTerribleI** [comment]
@Rydian Sorry, you are right of course- a lot of older video games were composed that way, and even novadays there are probably games/products that use it. I'm more talking about my experience from the music side of things- I'm involved in a music scene, and I would struggle name you one person I know who used a tracker before. All of your example are from the older games, and I'm sure there is an army of hardcore old-school people still having the knowledge- just not the younger generation of people coming up in music industry.

@ebering Ok thanks! And yeah, I'm not familiar with the devs unfortunately so I wouldn't know where to start. I'm content with waiting for now and seeing if someone shows up. We are 100% commited to making music when the time comes but I'd rather not engage right now into mass-messaging people who I don't know - I get to do that enough as it is running a studio =)

**Comment by ufshaikh** [comment]
Re making music depend on tension: I hope information relevant to the mechanics/gameplay will not be revealed to those who play with sound without that information also being somehow available to those who do not.

At a glance (I apologize if I am mistaken here) it looks like tension depends on information hidden to the player otherwise (hp, maxhp, and xp value of monsters in line of sight) and controls at least some behavior relevant to gameplay (e.g., god actions).

**Comment by Rydian** [comment]
As far as I know tension is primarily based on...

- Nearby monster difficulty.
- The player's HP.
- Status effects on the player and visible monsters.

HP and status effects are visible already.

Rough difficulty of monsters in sight is presented by their name color on the monster list for web tiles (white/yellow/red) so it's visible there... but I don't see it on the download tiles version (has a different UI) and don't know if it's displayed in any console version, is it some setting or something?

**Comment by ebering** [comment]
The submitters appear to have moved on to other projects and deleted their GitHub account. Absent a new composer or musician I'll close this.
