### ISSUE TITLE
Lua error with certain config with bindkey

### ISSUE THREAD

**Issue by rubenvereecken** [crawl/crawl#971]
**PLATFORM:**
Both local crawl-tiles and webtiles.

**VERSION:**
0.22, 0.23

**DESCRIPTION:**
I have an interesting Lua error pop up as soon as I start a game:
```
 Lua error: /dgldir/rcfiles/crawl-0.23/Randomaniac.rc:501: ')' expected (to close '(' at line 227) near 'CMD_CYCLE_QUIVER_BACKWARD'
```
You can see the full file at https://underhound.eu/crawl/rcfiles/crawl-0.23/Randomaniac.rc

Here is a reduced crawlrc that triggers it:
```
: if you.race() == "Ghoul" then
stop += smell.*(rott(ing|en)|decay)
: end

bindkey = []] CMD_CYCLE_QUIVER_BACKWARD
```
I don't see any parentheses that need closing however. Obviously `[]]` is a bit of an edge case, it doesn't happen with other bindings. But I really like being able to cycle through my quiver like that. Interestingly, it also doesn't happen if there are no Lua lines preceding it anywere. So really edge cases come together... it doesn't even prevent further parsing of the crawlrc file, so it's not even an important bug. But I thought I'd bring it up anyway.

**Comment by stenellad** [comment]
This bug is situated somewhere near 

https://github.com/crawl/crawl/blob/master/crawl-ref/source/initfile.cc#L1930
https://github.com/crawl/crawl/blob/master/crawl-ref/source/initfile.cc#L1945

The stack at the point before the Lua itself is run:
>	crawl.exe!dlua_chunk::run(CLua & interp) Line 181	C++
 	crawl.exe!game_options::read_options(LineInput & il, bool runscript, bool clear_aliases) Line 1946	C++
 	crawl.exe!read_init_file(bool runscript) Line 1652	C++
 	crawl.exe!_post_init(bool newc) Line 424	C++
 	crawl.exe!startup_step() Line 1389	C++
 	crawl.exe!_launch_game() Line 404	C++
 	crawl.exe!_launch_game_loop() Line 376	C++
 	crawl.exe!SDL_main(int argc, char * * argv) Line 332	C++
 	[Inline Frame] crawl.exe!main_utf8(int) Line 126	C
 	crawl.exe!main_getcmdline(...) Line 161	C

The Lua chunk sent to run inside Lua:

 	  if you.race() == "Ghoul" then
 	 crawl.setopt([[ stop += smell.*(rott(ing|en)|decay) ]])
 	  end
 	
 	 crawl.setopt([[ bindkey = [~] CMD_LUA_CONSOLE
 	 bindkey = []] CMD_CYCLE_QUIVER_BACKWARD ]])
